// ── ACB 약물 데이터베이스 ──────────────────────────────────────
// 참고: Boustani et al. (2008), Salahudeen et al. (2015), Kiesel et al. (2018)

const INGREDIENT_DB = [
  // ACB 0점 (Safe) — 엑셀 DB 기준 304종
{en:"Acarbose", kr:"아카보스", score:0, level:"Safe", classKR:"당뇨병 치료제"},
  {en:"Acetaminophen", kr:"아세트아미노펜", score:0, level:"Safe", classKR:"진통제"},
  {en:"Acetazolamide", kr:"아세타졸라미드", score:0, level:"Safe", classKR:"안과용제"},
  {en:"Acitretin", kr:"아시트레틴", score:0, level:"Safe", classKR:"피부과용제"},
  {en:"Acyclovir", kr:"아시클로버", score:0, level:"Safe", classKR:"항바이러스제"},
  {en:"Adenosine", kr:"아데노신", score:0, level:"Safe", classKR:"항부정맥제"},
  {en:"Alendronate", kr:"알렌드로네이트", score:0, level:"Safe", classKR:"골다공증 치료제"},
  {en:"Allopurinol", kr:"알로푸리놀", score:0, level:"Safe", classKR:"통풍 치료제"},
  {en:"Alverine", kr:"알베린", score:0, level:"Safe", classKR:"위장관 진경제"},
  {en:"Amiloride", kr:"아밀로라이드", score:0, level:"Safe", classKR:"이뇨제"},
  {en:"Amiodarone", kr:"아미오다론", score:0, level:"Safe", classKR:"항부정맥제"},
  {en:"Amlodipine", kr:"암로디핀", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Amoxicillin", kr:"아모시실린", score:0, level:"Safe", classKR:"항생제"},
  {en:"Ampicillin", kr:"암피실린", score:0, level:"Safe", classKR:"항생제"},
  {en:"Anagrelide", kr:"아나그렐리드", score:0, level:"Safe", classKR:"항종양제"},
  {en:"Anastrozole", kr:"아나스트로졸", score:0, level:"Safe", classKR:"항종양제"},
  {en:"Ascorbic acid", kr:"아스코르브산", score:0, level:"Safe", classKR:"비타민제"},
  {en:"Aspirin", kr:"아스피린", score:0, level:"Safe", classKR:"진통제"},
  {en:"Atenolol", kr:"아테놀롤", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Atorvastatin", kr:"아토르바스타틴", score:0, level:"Safe", classKR:"고지혈증 치료제"},
  {en:"Azathioprine", kr:"아자티오프린", score:0, level:"Safe", classKR:"면역억제제"},
  {en:"Azelastine", kr:"아젤라스틴", score:0, level:"Safe", classKR:"항히스타민제"},
  {en:"Azithromycin", kr:"아지트로마이신", score:0, level:"Safe", classKR:"항생제"},
  {en:"Benzonatate", kr:"벤조나테이트", score:0, level:"Safe", classKR:"진해제"},
  {en:"Bepotastine", kr:"베포타스틴", score:0, level:"Safe", classKR:"항히스타민제"},
  {en:"Beta-carotene", kr:"베타카로틴", score:0, level:"Safe", classKR:"비타민제"},
  {en:"Betahistine", kr:"베타히스틴", score:0, level:"Safe", classKR:"항현훈제"},
  {en:"Betaine", kr:"베타인", score:0, level:"Safe", classKR:"소화제"},
  {en:"Betaxolol", kr:"베탁솔롤", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Bethanechol", kr:"베타네콜", score:0, level:"Safe", classKR:"콜린제"},
  {en:"Bicalutamide", kr:"비칼루타미드", score:0, level:"Safe", classKR:"항종양제"},
  {en:"Bisacodyl", kr:"비사코딜", score:0, level:"Safe", classKR:"하제"},
  {en:"Bisoprolol", kr:"비소프롤롤", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Bromhexine", kr:"브롬헥신", score:0, level:"Safe", classKR:"거담제"},
  {en:"Bromocriptine", kr:"브로모크립틴", score:0, level:"Safe", classKR:"항파킨슨제"},
  {en:"Buprenorphine", kr:"부프레노르핀", score:0, level:"Safe", classKR:"진통제"},
  {en:"Cabergoline", kr:"카베골린", score:0, level:"Safe", classKR:"항파킨슨제"},
  {en:"Caffeine", kr:"카페인", score:0, level:"Safe", classKR:"중추신경자극제"},
  {en:"Calcitriol", kr:"칼시트리올", score:0, level:"Safe", classKR:"비타민제"},
  {en:"Candesartan", kr:"칸데사르탄", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Captopril", kr:"캡토프릴", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Carnitine", kr:"카르니틴", score:0, level:"Safe", classKR:"대사성 약물"},
  {en:"Carvedilol", kr:"카르베딜롤", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Casanthranol", kr:"카산트라놀", score:0, level:"Safe", classKR:"하제"},
  {en:"Cefaclor", kr:"세파클러", score:0, level:"Safe", classKR:"항생제"},
  {en:"Cefamandole", kr:"세파만돌", score:0, level:"Safe", classKR:"항생제"},
  {en:"Cefazolin", kr:"세파졸린", score:0, level:"Safe", classKR:"항생제"},
  {en:"Cefixime", kr:"세픽심", score:0, level:"Safe", classKR:"항생제"},
  {en:"Cefoxitin", kr:"세포시틴", score:0, level:"Safe", classKR:"항생제"},
  {en:"Ceftriaxone", kr:"세프트리아손", score:0, level:"Safe", classKR:"항생제"},
  {en:"Cefuroxime", kr:"세푸록심", score:0, level:"Safe", classKR:"항생제"},
  {en:"Celecoxib", kr:"세레콕시브", score:0, level:"Safe", classKR:"진통제"},
  {en:"Cephalexin", kr:"세팔렉신", score:0, level:"Safe", classKR:"항생제"},
  {en:"Cephalothin", kr:"세팔로틴", score:0, level:"Safe", classKR:"항생제"},
  {en:"Chlorambucil", kr:"클로람부실", score:0, level:"Safe", classKR:"항종양제"},
  {en:"Chlorthalidone", kr:"클로르탈리돈", score:0, level:"Safe", classKR:"이뇨제"},
  {en:"Chlorzoxazone", kr:"클로르족사존", score:0, level:"Safe", classKR:"근이완제"},
  {en:"Cholestyramine", kr:"콜레스티라민", score:0, level:"Safe", classKR:"고지혈증 치료제"},
  {en:"Chondroitin", kr:"콘드로이틴", score:0, level:"Safe", classKR:"연골보호제"},
  {en:"Cilostazol", kr:"실로스타졸", score:0, level:"Safe", classKR:"항혈소판제"},
  {en:"Ciprofloxacin", kr:"시프로플록사신", score:0, level:"Safe", classKR:"항생제"},
  {en:"Clarithromycin", kr:"클래리스로마이신", score:0, level:"Safe", classKR:"항생제"},
  {en:"Clindamycin", kr:"클린다마이신", score:0, level:"Safe", classKR:"항생제"},
  {en:"Clonidine", kr:"클로니딘", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Colchicine", kr:"콜히친", score:0, level:"Safe", classKR:"통풍 치료제"},
  {en:"Cyanocobalamin", kr:"시아노코발라민", score:0, level:"Safe", classKR:"비타민제"},
  {en:"Cyclophosphamide", kr:"사이클로포스파미드", score:0, level:"Safe", classKR:"항종양제"},
  {en:"Cycloserine", kr:"사이클로세린", score:0, level:"Safe", classKR:"항결핵제"},
  {en:"Cyclosporine", kr:"사이클로스포린", score:0, level:"Safe", classKR:"면역억제제"},
  {en:"Danazol", kr:"다나졸", score:0, level:"Safe", classKR:"성호르몬제"},
  {en:"Dantrolene", kr:"단트롤렌", score:0, level:"Safe", classKR:"근이완제"},
  {en:"Darbepoetin", kr:"다베포에틴", score:0, level:"Safe", classKR:"조혈제"},
  {en:"Deferasirox", kr:"데페라시록스", score:0, level:"Safe", classKR:"킬레이트제"},
  {en:"Dextran", kr:"덱스트란", score:0, level:"Safe", classKR:"혈장증량제"},
  {en:"Diclofenac", kr:"디클로페낙", score:0, level:"Safe", classKR:"진통제"},
  {en:"Diltiazem", kr:"딜티아젬", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Dirithromycin", kr:"디리트로마이신", score:0, level:"Safe", classKR:"항생제"},
  {en:"Dobutamine", kr:"도부타민", score:0, level:"Safe", classKR:"강심제"},
  {en:"Docusate", kr:"도큐세이트", score:0, level:"Safe", classKR:"하제"},
  {en:"Domperidone", kr:"돔페리돈", score:0, level:"Safe", classKR:"위장관운동조절제"},
  {en:"Donepezil", kr:"도네페질", score:0, level:"Safe", classKR:"항치매제"},
  {en:"Dopamine", kr:"도파민", score:0, level:"Safe", classKR:"강심제"},
  {en:"Doxazosin", kr:"독사조신", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Doxycycline", kr:"독시사이클린", score:0, level:"Safe", classKR:"항생제"},
  {en:"Duloxetine", kr:"둘록세틴", score:0, level:"Safe", classKR:"항우울제"},
  {en:"Dydrogesterone", kr:"디드로게스테론", score:0, level:"Safe", classKR:"성호르몬제"},
  {en:"Ebastine", kr:"에바스틴", score:0, level:"Safe", classKR:"항히스타민제"},
  {en:"Enalapril", kr:"에날라프릴", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Entacapone", kr:"엔타카폰", score:0, level:"Safe", classKR:"항파킨슨제"},
  {en:"Eperisone", kr:"에페리손", score:0, level:"Safe", classKR:"근이완제"},
  {en:"Epinastine", kr:"에피나스틴", score:0, level:"Safe", classKR:"항히스타민제"},
  {en:"Epinephrine", kr:"에피네프린", score:0, level:"Safe", classKR:"승압제"},
  {en:"Epoetin alfa", kr:"에포에틴 알파", score:0, level:"Safe", classKR:"조혈제"},
  {en:"Eprosartan", kr:"에프로사르탄", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Ergocalciferol", kr:"에르고칼시페롤", score:0, level:"Safe", classKR:"비타민제"},
  {en:"Ergoloid mesylates", kr:"에르고로이드메실산염", score:0, level:"Safe", classKR:"혈관확장제"},
  {en:"Erythromycin", kr:"에리트로마이신", score:0, level:"Safe", classKR:"항생제"},
  {en:"Esomeprazole", kr:"에스오메프라졸", score:0, level:"Safe", classKR:"위산분비억제"},
  {en:"Estrogen preparation", kr:"에스트로겐 제제", score:0, level:"Safe", classKR:"성호르몬제"},
  {en:"Ethambutol", kr:"에탐부톨", score:0, level:"Safe", classKR:"항결핵제"},
  {en:"Etidronate", kr:"에티드로네이트", score:0, level:"Safe", classKR:"골다공증 치료제"},
  {en:"Etodolac", kr:"에토돌락", score:0, level:"Safe", classKR:"진통제"},
  {en:"Ezetimibe", kr:"에제티미브", score:0, level:"Safe", classKR:"고지혈증 치료제"},
  {en:"Famciclovir", kr:"팜시클로버", score:0, level:"Safe", classKR:"항바이러스제"},
  {en:"Famotidine", kr:"파모티딘", score:0, level:"Safe", classKR:"위산분비억제"},
  {en:"Felodipine", kr:"펠로디핀", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Fenofibrate", kr:"페노피브레이트", score:0, level:"Safe", classKR:"고지혈증 치료제"},
  {en:"Fenoverine", kr:"페노베린", score:0, level:"Safe", classKR:"위장관 진경제"},
  {en:"Fexofenadine", kr:"펙소페나딘", score:0, level:"Safe", classKR:"항히스타민제"},
  {en:"Filgrastim", kr:"필그라스팀", score:0, level:"Safe", classKR:"조혈제"},
  {en:"Finasteride", kr:"피나스테리드", score:0, level:"Safe", classKR:"전립선비대증 치료제"},
  {en:"Fish oil", kr:"어유", score:0, level:"Safe", classKR:"지질조절제"},
  {en:"Flecainide", kr:"플레카이니드", score:0, level:"Safe", classKR:"항부정맥제"},
  {en:"Fluconazole", kr:"플루코나졸", score:0, level:"Safe", classKR:"항진균제"},
  {en:"Flumazenil", kr:"플루마제닐", score:0, level:"Safe", classKR:"해독제"},
  {en:"Fluorouracil", kr:"플루오로우라실", score:0, level:"Safe", classKR:"항종양제"},
  {en:"Flutamide", kr:"플루타미드", score:0, level:"Safe", classKR:"항종양제"},
  {en:"Fluvastatin", kr:"플루바스타틴", score:0, level:"Safe", classKR:"고지혈증 치료제"},
  {en:"Folic acid", kr:"엽산", score:0, level:"Safe", classKR:"비타민제"},
  {en:"Fosinopril", kr:"포시노프릴", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Frangula", kr:"프랑굴라", score:0, level:"Safe", classKR:"하제"},
  {en:"Gabapentin", kr:"가바펜틴", score:0, level:"Safe", classKR:"항전간제"},
  {en:"Galantamine", kr:"갈란타민", score:0, level:"Safe", classKR:"항치매제"},
  {en:"Gemfibrozil", kr:"겜피브로질", score:0, level:"Safe", classKR:"고지혈증 치료제"},
  {en:"Gentamicin", kr:"젠타마이신", score:0, level:"Safe", classKR:"항생제"},
  {en:"Ginkgo", kr:"은행엽엑스", score:0, level:"Safe", classKR:"항치매제"},
  {en:"Ginseng", kr:"인삼", score:0, level:"Safe", classKR:"생약제제"},
  {en:"Glibenclamide", kr:"글리벤클라미드", score:0, level:"Safe", classKR:"당뇨병 치료제"},
  {en:"Gliclazide", kr:"글리클라지드", score:0, level:"Safe", classKR:"당뇨병 치료제"},
  {en:"Glimepiride", kr:"글리메피리드", score:0, level:"Safe", classKR:"당뇨병 치료제"},
  {en:"Glipizide", kr:"글리피지드", score:0, level:"Safe", classKR:"당뇨병 치료제"},
  {en:"Glucosamine", kr:"글루코사민", score:0, level:"Safe", classKR:"연골보호제"},
  {en:"Glucose", kr:"포도당", score:0, level:"Safe", classKR:"영양제"},
  {en:"Goserelin acetate", kr:"고세렐린", score:0, level:"Safe", classKR:"항종양제"},
  {en:"Histidine", kr:"히스티딘", score:0, level:"Safe", classKR:"아미노산제"},
  {en:"Hydrochlorothiazide", kr:"히드로클로로티아지드", score:0, level:"Safe", classKR:"이뇨제"},
  {en:"Hydromorphone", kr:"하이드로모르폰", score:0, level:"Safe", classKR:"진통제"},
  {en:"Hydroxychloroquine", kr:"히드록시클로로퀸", score:0, level:"Safe", classKR:"항류마티스제"},
  {en:"Hydroxyurea", kr:"하이드록시우레아", score:0, level:"Safe", classKR:"항종양제"},
  {en:"Ibuprofen", kr:"이부프로펜", score:0, level:"Safe", classKR:"진통제"},
  {en:"Imipenem", kr:"이미페넴", score:0, level:"Safe", classKR:"항생제"},
  {en:"Indapamide", kr:"인다파미드", score:0, level:"Safe", classKR:"이뇨제"},
  {en:"Influenza virus vaccine", kr:"인플루엔자 백신", score:0, level:"Safe", classKR:"백신"},
  {en:"Insulin", kr:"인슐린", score:0, level:"Safe", classKR:"당뇨병 치료제"},
  {en:"Irbesartan", kr:"이르베사르탄", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Iron preparations", kr:"철분 제제", score:0, level:"Safe", classKR:"철분제제"},
  {en:"Isoniazid", kr:"이소니아지드", score:0, level:"Safe", classKR:"항결핵제"},
  {en:"Isosorbide", kr:"이소소르비드", score:0, level:"Safe", classKR:"항협심증제"},
  {en:"Ketoprofen", kr:"케토프로펜", score:0, level:"Safe", classKR:"진통제"},
  {en:"Ketorolac", kr:"케토롤락", score:0, level:"Safe", classKR:"진통제"},
  {en:"Labetalol", kr:"라베탈롤", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Lactic acid bacteria", kr:"유산균", score:0, level:"Safe", classKR:"정장제"},
  {en:"Lactulose", kr:"락툴로오스", score:0, level:"Safe", classKR:"하제"},
  {en:"Lamotrigine", kr:"라모트리진", score:0, level:"Safe", classKR:"항전간제"},
  {en:"Lansoprazole", kr:"란소프라졸", score:0, level:"Safe", classKR:"위산분비억제"},
  {en:"Lercanidipine", kr:"레르카니디핀", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Leuprolide", kr:"류프롤라이드", score:0, level:"Safe", classKR:"항종양제"},
  {en:"Levetiracetam", kr:"레비티라세탐", score:0, level:"Safe", classKR:"항전간제"},
  {en:"Levodopa/decarboxylase inhibitor", kr:"레보도파/탈탄산효소 억제제", score:0, level:"Safe", classKR:"항파킨슨제"},
  {en:"Levofloxacin", kr:"레보플록사신", score:0, level:"Safe", classKR:"항생제"},
  {en:"Lidocaine", kr:"리도카인", score:0, level:"Safe", classKR:"국소마취제"},
  {en:"Lisinopril", kr:"리시노프릴", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Lithium", kr:"리튬", score:0, level:"Safe", classKR:"항정신병약"},
  {en:"Losartan", kr:"로사르탄", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Lovastatin", kr:"로바스타틴", score:0, level:"Safe", classKR:"고지혈증 치료제"},
  {en:"Magnesium preparations", kr:"마그네슘 제제", score:0, level:"Safe", classKR:"제산제"},
  {en:"Mannitol", kr:"만니톨", score:0, level:"Safe", classKR:"이뇨제"},
  {en:"Medroxyprogesterone", kr:"메드록시프로게스테론", score:0, level:"Safe", classKR:"성호르몬제"},
  {en:"Megestrol", kr:"메게스트롤", score:0, level:"Safe", classKR:"성호르몬제"},
  {en:"Meloxicam", kr:"멜록시캄", score:0, level:"Safe", classKR:"진통제"},
  {en:"Memantine", kr:"메만틴", score:0, level:"Safe", classKR:"항치매제"},
  {en:"Mesalazine", kr:"메살라진", score:0, level:"Safe", classKR:"항염증제"},
  {en:"Metformin", kr:"메트포르민", score:0, level:"Safe", classKR:"당뇨병 치료제"},
  {en:"Methotrexate", kr:"메토트렉세이트", score:0, level:"Safe", classKR:"항종양제"},
  {en:"Methylcellulose", kr:"메틸셀룰로오스", score:0, level:"Safe", classKR:"안과용제"},
  {en:"Methylene blue", kr:"메틸렌블루", score:0, level:"Safe", classKR:"해독제"},
  {en:"Methylphenidate", kr:"메틸페니데이트", score:0, level:"Safe", classKR:"중추신경자극제"},
  {en:"Metoclopramide", kr:"메토클로프라미드", score:0, level:"Safe", classKR:"위장관운동조절제"},
  {en:"Metolazone", kr:"메톨라존", score:0, level:"Safe", classKR:"이뇨제"},
  {en:"Metoprolol", kr:"메토프롤롤", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Metronidazole", kr:"메트로니다졸", score:0, level:"Safe", classKR:"항생제"},
  {en:"Mexiletine", kr:"멕실레틴", score:0, level:"Safe", classKR:"항부정맥제"},
  {en:"Midodrine", kr:"미도드린", score:0, level:"Safe", classKR:"승압제"},
  {en:"Minocycline", kr:"미노사이클린", score:0, level:"Safe", classKR:"항생제"},
  {en:"Misoprostol", kr:"미소프로스톨", score:0, level:"Safe", classKR:"위점막보호제"},
  {en:"Mizolastine", kr:"미졸라스틴", score:0, level:"Safe", classKR:"항히스타민제"},
  {en:"Modafinil", kr:"모다피닐", score:0, level:"Safe", classKR:"중추신경자극제"},
  {en:"Moexipril", kr:"모엑시프릴", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Montelukast", kr:"몬테루카스트", score:0, level:"Safe", classKR:"천식 치료제"},
  {en:"Moxifloxacin", kr:"목시플록사신", score:0, level:"Safe", classKR:"항생제"},
  {en:"Multivitamin", kr:"종합비타민", score:0, level:"Safe", classKR:"비타민제"},
  {en:"N-acetyl-l-cysteine", kr:"아세틸시스테인", score:0, level:"Safe", classKR:"거담제"},
  {en:"Nabumetone", kr:"나부메톤", score:0, level:"Safe", classKR:"진통제"},
  {en:"Naloxone", kr:"날록손", score:0, level:"Safe", classKR:"해독제"},
  {en:"Naproxen", kr:"나프록센", score:0, level:"Safe", classKR:"진통제"},
  {en:"Naratriptan", kr:"나라트립탄", score:0, level:"Safe", classKR:"진통제"},
  {en:"Nateglinide", kr:"나테글리니드", score:0, level:"Safe", classKR:"당뇨병 치료제"},
  {en:"Nemonapride", kr:"네모나프리드", score:0, level:"Safe", classKR:"항정신병약"},
  {en:"Niacin", kr:"니아신", score:0, level:"Safe", classKR:"비타민제"},
  {en:"Nifedipine", kr:"니페디핀", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Nisoldipine", kr:"니솔디핀", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Nitrofurantoin", kr:"니트로푸란토인", score:0, level:"Safe", classKR:"항생제"},
  {en:"Nitroglycerin", kr:"니트로글리세린", score:0, level:"Safe", classKR:"항협심증제"},
  {en:"Nizatidine", kr:"니자티딘", score:0, level:"Safe", classKR:"위산분비억제"},
  {en:"Norepinephrine", kr:"노르에피네프린", score:0, level:"Safe", classKR:"승압제"},
  {en:"Norethisterone", kr:"노르에티스테론", score:0, level:"Safe", classKR:"성호르몬제"},
  {en:"Norfloxacin", kr:"노르플록사신", score:0, level:"Safe", classKR:"항생제"},
  {en:"Nystatin", kr:"니스타틴", score:0, level:"Safe", classKR:"항진균제"},
  {en:"Ofloxacin", kr:"오플록사신", score:0, level:"Safe", classKR:"항생제"},
  {en:"Olmesartan", kr:"올메사르탄", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Olopatadine", kr:"올로파타딘", score:0, level:"Safe", classKR:"항히스타민제"},
  {en:"Omeprazole", kr:"오메프라졸", score:0, level:"Safe", classKR:"위산분비억제"},
  {en:"Oxatomide", kr:"옥사토미드", score:0, level:"Safe", classKR:"항히스타민제"},
  {en:"Pamidronate", kr:"파미드로네이트", score:0, level:"Safe", classKR:"골다공증 치료제"},
  {en:"Pancrelipase", kr:"판크레리파아제", score:0, level:"Safe", classKR:"소화제"},
  {en:"Pantoprazole", kr:"판토프라졸", score:0, level:"Safe", classKR:"위산분비억제"},
  {en:"Papaverine", kr:"파파베린", score:0, level:"Safe", classKR:"위장관 진경제"},
  {en:"Pentazocine", kr:"펜타조신", score:0, level:"Safe", classKR:"진통제"},
  {en:"Pentoxifylline", kr:"펜톡시필린", score:0, level:"Safe", classKR:"혈관확장제"},
  {en:"Perindopril", kr:"페린도프릴", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Phenobarbital", kr:"페노바르비탈", score:0, level:"Safe", classKR:"항전간제"},
  {en:"Phenylephrine", kr:"페닐에프린", score:0, level:"Safe", classKR:"비충혈제거제"},
  {en:"Phenytoin", kr:"페니토인", score:0, level:"Safe", classKR:"항전간제"},
  {en:"Phytonadione", kr:"피토나디온", score:0, level:"Safe", classKR:"비타민제"},
  {en:"Pilocarpine", kr:"필로카르핀", score:0, level:"Safe", classKR:"안과용제"},
  {en:"Pioglitazone", kr:"피오글리타존", score:0, level:"Safe", classKR:"당뇨병 치료제"},
  {en:"Piperacillin", kr:"피페라실린", score:0, level:"Safe", classKR:"항생제"},
  {en:"Piroxicam", kr:"피록시캄", score:0, level:"Safe", classKR:"진통제"},
  {en:"Polycarbophil", kr:"폴리카르보필", score:0, level:"Safe", classKR:"하제"},
  {en:"Potassium", kr:"칼륨", score:0, level:"Safe", classKR:"미네랄제제"},
  {en:"Pramipexole", kr:"프라미펙솔", score:0, level:"Safe", classKR:"항파킨슨제"},
  {en:"Pravastatin", kr:"프라바스타틴", score:0, level:"Safe", classKR:"고지혈증 치료제"},
  {en:"Primidone", kr:"프리미돈", score:0, level:"Safe", classKR:"항전간제"},
  {en:"Progesterone", kr:"프로게스테론", score:0, level:"Safe", classKR:"성호르몬제"},
  {en:"Propafenone", kr:"프로파페논", score:0, level:"Safe", classKR:"항부정맥제"},
  {en:"Propranolol", kr:"프로프라놀롤", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Protamine", kr:"프로타민", score:0, level:"Safe", classKR:"해독제"},
  {en:"Pseudoephedrine", kr:"슈도에페드린", score:0, level:"Safe", classKR:"비충혈제거제"},
  {en:"Psyllium", kr:"차전자피", score:0, level:"Safe", classKR:"하제"},
  {en:"Pyrazinamide", kr:"피라진아미드", score:0, level:"Safe", classKR:"항결핵제"},
  {en:"Pyridostigmine", kr:"피리도스티그민", score:0, level:"Safe", classKR:"콜린제"},
  {en:"Pyridoxine", kr:"피리독신", score:0, level:"Safe", classKR:"비타민제"},
  {en:"Quinapril", kr:"퀴나프릴", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Rabeprazole", kr:"라베프라졸", score:0, level:"Safe", classKR:"위산분비억제"},
  {en:"Raloxifene", kr:"랄록시펜", score:0, level:"Safe", classKR:"골다공증 치료제"},
  {en:"Ramipril", kr:"라미프릴", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Repaglinide", kr:"레파글리니드", score:0, level:"Safe", classKR:"당뇨병 치료제"},
  {en:"Rifampicin", kr:"리팜피신", score:0, level:"Safe", classKR:"항결핵제"},
  {en:"Risedronate", kr:"리세드로네이트", score:0, level:"Safe", classKR:"골다공증 치료제"},
  {en:"Rivastigmine", kr:"리바스티그민", score:0, level:"Safe", classKR:"항치매제"},
  {en:"Ropinirole", kr:"로피니롤", score:0, level:"Safe", classKR:"항파킨슨제"},
  {en:"Rosiglitazone", kr:"로시글리타존", score:0, level:"Safe", classKR:"당뇨병 치료제"},
  {en:"Rosuvastatin", kr:"로수바스타틴", score:0, level:"Safe", classKR:"고지혈증 치료제"},
  {en:"Roxithromycin", kr:"록시트로마이신", score:0, level:"Safe", classKR:"항생제"},
  {en:"Salbutamol", kr:"살부타몰", score:0, level:"Safe", classKR:"기관지확장제"},
  {en:"Salsalate", kr:"살살레이트", score:0, level:"Safe", classKR:"진통제"},
  {en:"Selegiline", kr:"셀레길린", score:0, level:"Safe", classKR:"항파킨슨제"},
  {en:"Senna", kr:"센나", score:0, level:"Safe", classKR:"하제"},
  {en:"Sertraline", kr:"설트랄린", score:0, level:"Safe", classKR:"항우울제"},
  {en:"Sildenafil", kr:"실데나필", score:0, level:"Safe", classKR:"발기부전 치료제"},
  {en:"Simethicone", kr:"시메티콘", score:0, level:"Safe", classKR:"가스제거제"},
  {en:"Simvastatin", kr:"심바스타틴", score:0, level:"Safe", classKR:"고지혈증 치료제"},
  {en:"Sodium bicarbonate", kr:"탄산수소나트륨", score:0, level:"Safe", classKR:"제산제"},
  {en:"Sodium chloride", kr:"염화나트륨", score:0, level:"Safe", classKR:"전해질보충제"},
  {en:"Sotalol", kr:"소탈롤", score:0, level:"Safe", classKR:"항부정맥제"},
  {en:"Spironolactone", kr:"스피로놀락톤", score:0, level:"Safe", classKR:"이뇨제"},
  {en:"Succinylcholine", kr:"숙시닐콜린", score:0, level:"Safe", classKR:"근이완제"},
  {en:"Sucralfate", kr:"수크랄페이트", score:0, level:"Safe", classKR:"위점막보호제"},
  {en:"Sulfamethoxazole-trimethoprim", kr:"코트리목사졸", score:0, level:"Safe", classKR:"항생제"},
  {en:"Sulfasalazine", kr:"설파살라진", score:0, level:"Safe", classKR:"항염증제"},
  {en:"Sulindac", kr:"설린닥", score:0, level:"Safe", classKR:"진통제"},
  {en:"Sumatriptan", kr:"수마트립탄", score:0, level:"Safe", classKR:"진통제"},
  {en:"Tadalafil", kr:"타다라필", score:0, level:"Safe", classKR:"발기부전 치료제"},
  {en:"Tamoxifen", kr:"타목시펜", score:0, level:"Safe", classKR:"항종양제"},
  {en:"Tamsulosin", kr:"탐스로신", score:0, level:"Safe", classKR:"전립선비대증 치료제"},
  {en:"Telmisartan", kr:"텔미사르탄", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Terazosin", kr:"테라조신", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Terbinafine", kr:"테르비나핀", score:0, level:"Safe", classKR:"항진균제"},
  {en:"Testosterone", kr:"테스토스테론", score:0, level:"Safe", classKR:"성호르몬제"},
  {en:"Tetracycline", kr:"테트라사이클린", score:0, level:"Safe", classKR:"항생제"},
  {en:"Thiamine", kr:"티아민", score:0, level:"Safe", classKR:"비타민제"},
  {en:"Tianeptine", kr:"티아넵틴", score:0, level:"Safe", classKR:"항우울제"},
  {en:"Tiaprofenic acid", kr:"티아프로펜산", score:0, level:"Safe", classKR:"진통제"},
  {en:"Tibolone", kr:"티볼론", score:0, level:"Safe", classKR:"성호르몬제"},
  {en:"Timolol", kr:"티몰롤", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Tiropramide", kr:"티로프라미드", score:0, level:"Safe", classKR:"위장관 진경제"},
  {en:"Tocopherol", kr:"토코페롤", score:0, level:"Safe", classKR:"비타민제"},
  {en:"Tolperisone", kr:"톨페리손", score:0, level:"Safe", classKR:"근이완제"},
  {en:"Topiramate", kr:"토피라메이트", score:0, level:"Safe", classKR:"항전간제"},
  {en:"Torsemide", kr:"토르세미드", score:0, level:"Safe", classKR:"이뇨제"},
  {en:"Triamterene", kr:"트리암테렌", score:0, level:"Safe", classKR:"이뇨제"},
  {en:"Tuberculin purified protein derivate", kr:"튜베르쿨린", score:0, level:"Safe", classKR:"진단용약"},
  {en:"Ubidecarenone", kr:"유비데카레논", score:0, level:"Safe", classKR:"항산화제"},
  {en:"Ursodiol", kr:"우르소데옥시콜산", score:0, level:"Safe", classKR:"이담제"},
  {en:"Valproic acid", kr:"발프로산", score:0, level:"Safe", classKR:"항전간제"},
  {en:"Valsartan", kr:"발사르탄", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Vancomycin", kr:"반코마이신", score:0, level:"Safe", classKR:"항생제"},
  {en:"Vardenafil", kr:"바데나필", score:0, level:"Safe", classKR:"발기부전 치료제"},
  {en:"Varenicline", kr:"바레니클린", score:0, level:"Safe", classKR:"금연보조제"},
  {en:"Vecuronium", kr:"베쿠로늄", score:0, level:"Safe", classKR:"근이완제"},
  {en:"Verapamil", kr:"베라파밀", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Zafirlukast", kr:"자피를루카스트", score:0, level:"Safe", classKR:"천식 치료제"},
  {en:"Zinc preparations", kr:"아연 제제", score:0, level:"Safe", classKR:"미네랄제제"},
  {en:"Zolmitriptan", kr:"졸미트립탄", score:0, level:"Safe", classKR:"진통제"},
  
  // ACB 3점 (Strong) — 엑셀 DB 기준 41종
  {en:"Amitriptyline",      kr:"아미트리프틸린",        score:3, level:"Strong",   classKR:"삼환계 항우울제"},
  {en:"Atropine",           kr:"아트로핀",              score:3, level:"Strong",   classKR:"진경제/항무스카린제"},
  {en:"Benztropine",        kr:"벤즈트로핀",            score:3, level:"Strong",   classKR:"항파킨슨제"},
  {en:"Brompheniramine",    kr:"브롬페니라민",           score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Carbinoxamine",      kr:"카르비녹사민",           score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Chlorpheniramine",   kr:"클로르페니라민",         score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Chlorpromazine",     kr:"클로르프로마진",         score:3, level:"Strong",   classKR:"항정신병약"},
  {en:"Cimetropium",        kr:"시메트로피움",           score:3, level:"Strong",   classKR:"위장관 진경제"},
  {en:"Clemastine",         kr:"클레마스틴",             score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Clomipramine",       kr:"클로미프라민",           score:3, level:"Strong",   classKR:"삼환계 항우울제"},
  {en:"Clozapine",          kr:"클로자핀",               score:3, level:"Strong",   classKR:"비정형 항정신병제"},
  {en:"Dexbrompheniramine", kr:"덱스브롬페니라민",       score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Dexchlorpheniramine",kr:"덱스클로르페니라민",     score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Dicyclomine",        kr:"디사이클로민",           score:3, level:"Strong",   classKR:"위장관 진경제"},
  {en:"Dimenhydrinate",     kr:"디멘히드리나이트",       score:3, level:"Strong",   classKR:"항구토제/항히스타민제"},
  {en:"Diphenhydramine",    kr:"디펜히드라민",           score:3, level:"Strong",   classKR:"항히스타민제/수면유도"},
  {en:"Doxepin",            kr:"독세핀",                 score:3, level:"Strong",   classKR:"삼환계 항우울제"},
  {en:"Doxylamine",         kr:"독실아민",               score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Fesoterodine",       kr:"페소테로딘",             score:3, level:"Strong",   classKR:"과민성 방광 치료제"},
  {en:"Flavoxate",          kr:"플라복세이트",           score:3, level:"Strong",   classKR:"비뇨기계 진경제"},
  {en:"Hydroxyzine",        kr:"히드록시진",             score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Imidafenacin",       kr:"이미다페나신",           score:3, level:"Strong",   classKR:"비뇨기계 진경제"},
  {en:"Imipramine",         kr:"이미프라민",             score:3, level:"Strong",   classKR:"삼환계 항우울제"},
  {en:"Meclizine",          kr:"메클리진",               score:3, level:"Strong",   classKR:"항구토제/항현훈제"},
  {en:"Mequitazine",        kr:"메퀴타진",               score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Nortriptyline",      kr:"노르트립틸린",           score:3, level:"Strong",   classKR:"항우울제"},
  {en:"Octylonium bromide", kr:"옥틸로늄 브롬화물",       score:3, level:"Strong",   classKR:"위장관 진경제"},
  {en:"Olanzapine",         kr:"올란자핀",               score:3, level:"Strong",   classKR:"항정신병약"},
  {en:"Orphenadrine",       kr:"오르페나드린",           score:3, level:"Strong",   classKR:"근이완제"},
  {en:"Oxybutynin",         kr:"옥시부티닌",             score:3, level:"Strong",   classKR:"비뇨기계 진경제"},
  {en:"Pheniramine",        kr:"페니라민",               score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Pridinol",           kr:"프리디놀",               score:3, level:"Strong",   classKR:"근이완제"},
  {en:"Procyclidine",       kr:"프로사이클리딘",         score:3, level:"Strong",   classKR:"항파킨슨제"},
  {en:"Propiverine",        kr:"프로피베린",             score:3, level:"Strong",   classKR:"비뇨기계 진경제"},
  {en:"Pyrilamine",         kr:"피릴라민",               score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Scopolamine",        kr:"스코폴라민",             score:3, level:"Strong",   classKR:"항콜린제"},
  {en:"Scopolamine Butylbromide", kr:"스코폴라민 부틸브롬화물", score:3, level:"Strong", classKR:"위장관 진경제"},
  {en:"Solifenacin",        kr:"솔리페나신",             score:3, level:"Strong",   classKR:"비뇨기계 진경제"},
  {en:"Tolterodine",        kr:"톨테로딘",               score:3, level:"Strong",   classKR:"비뇨기계 진경제"},
  {en:"Trihexyphenidyl",    kr:"트리헥시페니딜",         score:3, level:"Strong",   classKR:"항파킨슨제"},
  {en:"Trospium",           kr:"트로스피움",             score:3, level:"Strong",   classKR:"비뇨기계 진경제"},

  // ACB 2점 (Moderate) — 엑셀 DB 기준 22종
  {en:"Amantadine",         kr:"아만타딘",               score:2, level:"Moderate", classKR:"항파킨슨제"},
  {en:"Cimetidine",         kr:"시메티딘",               score:2, level:"Moderate", classKR:"H2 차단제"},
  {en:"Clidinium",          kr:"클리디늄",               score:2, level:"Moderate", classKR:"위장관 항콜린제"},
  {en:"Cloperastine",       kr:"클로페라스틴",           score:2, level:"Moderate", classKR:"진해제"},
  {en:"Cyclobenzaprine",    kr:"사이클로벤자프린",       score:2, level:"Moderate", classKR:"근이완제"},
  {en:"Cyproheptadine",     kr:"사이프로헵타딘",         score:2, level:"Moderate", classKR:"항히스타민제"},
  {en:"Difenidol",          kr:"디페니돌",               score:2, level:"Moderate", classKR:"항현훈제"},
  {en:"Glycopyrrolate",     kr:"글리코피롤레이트",       score:2, level:"Moderate", classKR:"위장관 항콜린제"},
  {en:"Levomepromazine",    kr:"레보메프로마진",         score:2, level:"Moderate", classKR:"항정신병약"},
  {en:"Loxapine",           kr:"록사핀",                 score:2, level:"Moderate", classKR:"항정신병약"},
  {en:"Molindone",          kr:"몰린돈",                 score:2, level:"Moderate", classKR:"항정신병약"},
  {en:"Nefopam",            kr:"네포팜",                 score:2, level:"Moderate", classKR:"진통제"},
  {en:"Oxcarbazepine",      kr:"옥스카르바제핀",         score:2, level:"Moderate", classKR:"항전간제"},
  {en:"Paroxetine",         kr:"파록세틴",               score:2, level:"Moderate", classKR:"항우울제 (SSRI)"},
  {en:"Perphenazine",       kr:"퍼페나진",               score:2, level:"Moderate", classKR:"항정신병약"},
  {en:"Pethidine",          kr:"페티딘",                 score:2, level:"Moderate", classKR:"진통제"},
  {en:"Pimozide",           kr:"피모자이드",             score:2, level:"Moderate", classKR:"항정신병약"},
  {en:"Quetiapine",         kr:"쿠에티아핀",             score:2, level:"Moderate", classKR:"항정신병약"},
  {en:"Tizanidine",         kr:"티자니딘",               score:2, level:"Moderate", classKR:"근이완제"},
  {en:"Tramadol",           kr:"트라마돌",               score:2, level:"Moderate", classKR:"진통제"},
  {en:"Triprolidine",       kr:"트리프로리딘",           score:2, level:"Moderate", classKR:"항히스타민제"},
  {en:"Zotepine",           kr:"조테핀",                 score:2, level:"Moderate", classKR:"항정신병약"},

  // ACB 1점 (Weak) — 엑셀 DB 기준 50종
  {en:"Alprazolam",         kr:"알프라졸람",             score:1, level:"Weak",     classKR:"항불안제"},
  {en:"Amisulpride",        kr:"아미설프리드",           score:1, level:"Weak",     classKR:"항정신병약"},
  {en:"Aripiprazole",       kr:"아리피프라졸",           score:1, level:"Weak",     classKR:"항정신병약"},
  {en:"Baclofen",           kr:"바클로펜",               score:1, level:"Weak",     classKR:"근이완제"},
  {en:"Blonanserin",        kr:"블로난세린",             score:1, level:"Weak",     classKR:"항정신병약"},
  {en:"Bupropion",          kr:"부프로피온",             score:1, level:"Weak",     classKR:"항우울제"},
  {en:"Carbamazepine",      kr:"카르바마제핀",           score:1, level:"Weak",     classKR:"항경련제"},
  {en:"Cetirizine",         kr:"세티리진",               score:1, level:"Weak",     classKR:"항히스타민제"},
  {en:"Chlordiazepoxide",   kr:"클로르디아제폭사이드",   score:1, level:"Weak",     classKR:"항불안제"},
  {en:"Cinnarizine",        kr:"신나리진",               score:1, level:"Weak",     classKR:"항현훈제"},
  {en:"Citalopram",         kr:"시탈로프람",             score:1, level:"Weak",     classKR:"항우울제"},
  {en:"Clonazepam",         kr:"클로나제팜",             score:1, level:"Weak",     classKR:"항경련제/항불안제"},
  {en:"Codeine",            kr:"코데인",                 score:1, level:"Weak",     classKR:"진통제"},
  {en:"Desloratadine",      kr:"데슬로라타딘",           score:1, level:"Weak",     classKR:"항히스타민제"},
  {en:"Desvenlafaxine",     kr:"데스벤라팍신",           score:1, level:"Weak",     classKR:"항우울제 (SNRI)"},
  {en:"Dextromethorphan",   kr:"덱스트로메토르판",       score:1, level:"Weak",     classKR:"진해제"},
  {en:"Diazepam",           kr:"디아제팜",               score:1, level:"Weak",     classKR:"항불안제"},
  {en:"Digoxin",            kr:"디곡신",                 score:1, level:"Weak",     classKR:"강심제"},
  {en:"Emedastine",         kr:"에메다스틴",             score:1, level:"Weak",     classKR:"항히스타민제"},
  {en:"Escitalopram",       kr:"에스시탈로프람",         score:1, level:"Weak",     classKR:"항우울제"},
  {en:"Fentanyl",           kr:"펜타닐",                 score:1, level:"Weak",     classKR:"진통제"},
  {en:"Flunitrazepam",      kr:"플루니트라제팜",         score:1, level:"Weak",     classKR:"수면제"},
  {en:"Fluoxetine",         kr:"플루옥세틴",             score:1, level:"Weak",     classKR:"항우울제 (SSRI)"},
  {en:"Flurazepam",         kr:"플루라제팜",             score:1, level:"Weak",     classKR:"수면제"},
  {en:"Furosemide",         kr:"푸로세미드",             score:1, level:"Weak",     classKR:"이뇨제"},
  {en:"Guaifenesin",        kr:"구아이페네신",           score:1, level:"Weak",     classKR:"거담제"},
  {en:"Haloperidol",        kr:"할로페리돌",             score:1, level:"Weak",     classKR:"항정신병약"},
  {en:"Hydralazine",        kr:"하이드랄라진",           score:1, level:"Weak",     classKR:"혈압강하제"},
  {en:"Hydrocodone",        kr:"하이드로코돈",           score:1, level:"Weak",     classKR:"진통제"},
  {en:"Hydrocortisone",     kr:"하이드로코르티손",       score:1, level:"Weak",     classKR:"스테로이드"},
  {en:"Ketotifen",          kr:"케토티펜",               score:1, level:"Weak",     classKR:"항히스타민제"},
  {en:"Levocetirizine",     kr:"레보세티리진",           score:1, level:"Weak",     classKR:"항히스타민제"},
  {en:"Loperamide",         kr:"로페라마이드",           score:1, level:"Weak",     classKR:"지사제"},
  {en:"Loratadine",         kr:"로라타딘",               score:1, level:"Weak",     classKR:"항히스타민제"},
  {en:"Lorazepam",          kr:"로라제팜",               score:1, level:"Weak",     classKR:"항불안제"},
  {en:"Methocarbamol",      kr:"메토카르바몰",           score:1, level:"Weak",     classKR:"근이완제"},
  {en:"Midazolam",          kr:"미다졸람",               score:1, level:"Weak",     classKR:"진정제"},
  {en:"Mirtazapine",        kr:"미르타자핀",             score:1, level:"Weak",     classKR:"항우울제"},
  {en:"Morphine",           kr:"모르핀",                 score:1, level:"Weak",     classKR:"진통제"},
  {en:"Oxycodone",          kr:"옥시코돈",               score:1, level:"Weak",     classKR:"진통제"},
  {en:"Paliperidone",       kr:"팔리페리돈",             score:1, level:"Weak",     classKR:"항정신병약"},
  {en:"Prednisolone",       kr:"프레드니솔론",           score:1, level:"Weak",     classKR:"스테로이드"},
  {en:"Ranitidine",         kr:"라니티딘",               score:1, level:"Weak",     classKR:"위산분비억제"},
  {en:"Risperidone",        kr:"리스페리돈",             score:1, level:"Weak",     classKR:"항정신병약"},
  {en:"Theophylline",       kr:"테오필린",               score:1, level:"Weak",     classKR:"기관지확장제"},
  {en:"Trazodone",          kr:"트라조돈",               score:1, level:"Weak",     classKR:"항우울제/수면제"},
  {en:"Triazolam",          kr:"트리아졸람",             score:1, level:"Weak",     classKR:"수면제"},
  {en:"Trimebutine",        kr:"트리메부틴",             score:1, level:"Weak",     classKR:"위장관운동조절제"},
  {en:"Venlafaxine",        kr:"벤라팍신",               score:1, level:"Weak",     classKR:"항우울제 (SNRI)"},
  {en:"Ziprasidone",        kr:"지프라시돈",             score:1, level:"Weak",     classKR:"항정신병약"},
];

// ── 상품명 → 성분명 매핑 ─────────────────────────────────────
const BRAND_MAP = {
  // 3점 약물 상품명
  "에트라빌정":"Amitriptyline",
  "에나폰정":"Amitriptyline",
  "명인아미트리프틸린염산염정":"Amitriptyline",
  "대원황산아트로핀주사액":"Atropine",
  "대한아트로핀황산염주사액":"Atropine",
  "드림피아점안액0.125%(1회용)":"Atropine",
  "마이오가드점안액0.125%(1회용)":"Atropine",
  "마이오캡점안액0.125%(1회용)":"Atropine",
  "마이오텍트점안액(1회용)":"Atropine",
  "마이오텍트점안액0.125%(1회용)":"Atropine",
  "마이원점안액0.125%(1회용)":"Atropine",
  "삼양아트로핀주사제":"Atropine",
  "알콘아트로핀황산염1%점안제":"Atropine",
  "오큐호마핀점안액":"Atropine",
  "한림호마핀점안액":"Atropine",
  "명인벤즈트로핀메실산염정":"Benztropine",
  "환인벤즈트로핀정":"Benztropine",
  "그날엔노즈플러스연질캡슐":"Brompheniramine",
  "그날엔콜드플러스연질캡슐":"Brompheniramine",
  "래피콜데이연질캡슐":"Brompheniramine",
  "로나코연질캡슐":"Brompheniramine",
  "로나콜연질캡슐":"Brompheniramine",
  "벤포노즈연질캡슐":"Brompheniramine",
  "삐삐콜플러스정":"Brompheniramine",
  "엑쎈코연질캡슐":"Brompheniramine",
  "엔비쿨정":"Brompheniramine",
  "옴니콜노즈연질캡슐":"Brompheniramine",
  "캐롤비노즈연질캡슐":"Brompheniramine",
  "클리어콜노즈연질캡슐":"Brompheniramine",
  "판텍큐노즈플러스연질캡슐":"Brompheniramine",
  "판텍큐플러스연질캡슐":"Brompheniramine",
  "푸르노즈연질캡슐":"Brompheniramine",
  "하디큐노즈연질캡슐":"Brompheniramine",
  "화콜씨노즈연질캡슐":"Brompheniramine",
  "화콜씨콜드연질캡슐":"Brompheniramine",
  "그린콜샷리퀴드연질캡슐":"Carbinoxamine",
  "네오콜코프캡슐":"Carbinoxamine",
  "노스핀캡슐":"Carbinoxamine",
  "바스크롱에프캡슐":"Carbinoxamine",
  "센코프캡슐":"Carbinoxamine",
  "아스노캡슐":"Carbinoxamine",
  "아스콘에이캡슐":"Carbinoxamine",
  "에어로민캡슐":"Carbinoxamine",
  "에치탑캡슐":"Carbinoxamine",
  "엑스콜코프캡슐":"Carbinoxamine",
  "케어코프캡슐":"Carbinoxamine",
  "콜콜코프캡슐":"Carbinoxamine",
  "프리넥캡슐":"Carbinoxamine",
  "프리카바에프캡슐":"Carbinoxamine",
  "플루코프캡슐":"Carbinoxamine",
  "하드코프캡슐":"Carbinoxamine",
  "한신코푸담캡슐":"Carbinoxamine",
  "감바로과립":"Chlorpheniramine",
  "감콜씨플러스캡슐":"Chlorpheniramine",
  "고프레노즈연질캡슐":"Chlorpheniramine",
  "광동콜에스액":"Chlorpheniramine",
  "굿엔코액":"Chlorpheniramine",
  "굿엔콜액":"Chlorpheniramine",
  "그날엔노즈에이연질캡슐":"Chlorpheniramine",
  "그날엔노즈연질캡슐":"Chlorpheniramine",
  "그날엔코프에스연질캡슐":"Chlorpheniramine",
  "그날엔콜드에이연질캡슐":"Chlorpheniramine",
  "그날엔콜드연질캡슐":"Chlorpheniramine",
  "그린노즈에스시럽":"Chlorpheniramine",
  "그린노즈에스캡슐":"Chlorpheniramine",
  "그린노즈플러스연질캡슐":"Chlorpheniramine",
  "그린코푸에스캡슐":"Chlorpheniramine",
  "그린콜샷에스시럽":"Chlorpheniramine",
  "그린콜샷에스캡슐":"Chlorpheniramine",
  "그린콜연질캡슐":"Chlorpheniramine",
  "기가에이연질캡슐":"Chlorpheniramine",
  "기감탕노즈액":"Chlorpheniramine",
  "기치코프에스캡슐":"Chlorpheniramine",
  "나리스타에스점비액":"Chlorpheniramine",
  "나이스노즈연질캡슐":"Chlorpheniramine",
  "나이스코프연질캡슐":"Chlorpheniramine",
  "나이스콜드연질캡슐":"Chlorpheniramine",
  "나콜플러스시럽":"Chlorpheniramine",
  "나트콜연질캡슐":"Chlorpheniramine",
  "난타코연질캡슐":"Chlorpheniramine",
  "난타코프연질캡슐":"Chlorpheniramine",
  "난타콜연질캡슐":"Chlorpheniramine",
  "네오메디코푸정":"Chlorpheniramine",
  "네오코정":"Chlorpheniramine",
  "네오콜캡슐":"Chlorpheniramine",
  "네파졸점비액":"Chlorpheniramine",
  "노노콜캡슐":"Chlorpheniramine",
  "노량캡슐":"Chlorpheniramine",
  "노이제로정":"Chlorpheniramine",
  "노이텍정":"Chlorpheniramine",
  "노즈그린연질캡슐":"Chlorpheniramine",
  "노즈앤굿나잘스프레이":"Chlorpheniramine",
  "노즈케어점비액":"Chlorpheniramine",
  "노즈코프연질캡슐":"Chlorpheniramine",
  "노즈쿨점비액":"Chlorpheniramine",
  "노즈퀵구강용해필름":"Chlorpheniramine",
  "노즈파워연질캡슐":"Chlorpheniramine",
  "노즈포나잘스프레이":"Chlorpheniramine",
  "눈앤큐점안액":"Chlorpheniramine",
  "뉴브이로토이엑스점안액":"Chlorpheniramine",
  "뉴스코정":"Chlorpheniramine",
  "다나콜플러스캡슐":"Chlorpheniramine",
  "다이오친에프정":"Chlorpheniramine",
  "대원콜노즈연질캡슐":"Chlorpheniramine",
  "대원콜이부노즈연질캡슐":"Chlorpheniramine",
  "대원콜이부콜드연질캡슐":"Chlorpheniramine",
  "대원콜콜드연질캡슐":"Chlorpheniramine",
  "데이감에스정":"Chlorpheniramine",
  "델타콜에스과립":"Chlorpheniramine",
  "도브콜정":"Chlorpheniramine",
  "두캅스에이연질캡슐":"Chlorpheniramine",
  "둥근머리물팝스겔":"Chlorpheniramine",
  "듀얼콜시럽":"Chlorpheniramine",
  "디펜스코연질캡슐":"Chlorpheniramine",
  "디펜코정":"Chlorpheniramine",
  "디펜콜노즈시럽":"Chlorpheniramine",
  "디펜콜노즈캡슐":"Chlorpheniramine",
  "디펜콜에이캡슐":"Chlorpheniramine",
  "디펜콜콜드시럽":"Chlorpheniramine",
  "라그리펜정":"Chlorpheniramine",
  "락콜드노즈시럽":"Chlorpheniramine",
  "락콜드액":"Chlorpheniramine",
  "락콜드종합시럽":"Chlorpheniramine",
  "래피콜노즈연질캡슐":"Chlorpheniramine",
  "래피콜에이캡슐":"Chlorpheniramine",
  "래피콜케어건조시럽":"Chlorpheniramine",
  "래피콜코프연질캡슐":"Chlorpheniramine",
  "래피콜코프플러스연질캡슐":"Chlorpheniramine",
  "래피콜콜드연질캡슐":"Chlorpheniramine",
  "러지코정":"Chlorpheniramine",
  "레드넥콜연질캡슐":"Chlorpheniramine",
  "레드코프에프연질캡슐":"Chlorpheniramine",
  "레드콜에프연질캡슐":"Chlorpheniramine",
  "레드콜연질캡슐":"Chlorpheniramine",
  "레디고액":"Chlorpheniramine",
  "레티코연질캡슐":"Chlorpheniramine",
  "레티코이브연질캡슐":"Chlorpheniramine",
  "레티코포르테연질캡슐":"Chlorpheniramine",
  "레티코하이연질캡슐":"Chlorpheniramine",
  "레티콜연질캡슐":"Chlorpheniramine",
  "레티콜이브연질캡슐":"Chlorpheniramine",
  "레티콜플러스연질캡슐":"Chlorpheniramine",
  "레티콜하이연질캡슐":"Chlorpheniramine",
  "로토지파이뉴점안액":"Chlorpheniramine",
  "리노콜드시럽":"Chlorpheniramine",
  "리드콜연질캡슐":"Chlorpheniramine",
  "리드플루연질캡슐":"Chlorpheniramine",
  "마더스코연질캡슐":"Chlorpheniramine",
  "마더스콜드연질캡슐":"Chlorpheniramine",
  "마이톡톡케어점안액":"Chlorpheniramine",
  "마파람과립":"Chlorpheniramine",
  "맥시부펜노즈연질캡슐":"Chlorpheniramine",
  "맥시부펜콜드연질캡슐":"Chlorpheniramine",
  "메가코정":"Chlorpheniramine",
  "메가클린연질캡슐":"Chlorpheniramine",
  "메디코캡슐":"Chlorpheniramine",
  "메디콜캡슐":"Chlorpheniramine",
  "메타리빈큐액":"Chlorpheniramine",
  "모드나캡슐":"Chlorpheniramine",
  "모드알레나잘스프레이":"Chlorpheniramine",
  "모드코에스연질캡슐":"Chlorpheniramine",
  "모드콜노즈시럽":"Chlorpheniramine",
  "모드콜시럽":"Chlorpheniramine",
  "모드콜에스연질캡슐":"Chlorpheniramine",
  "모드콜코프시럽":"Chlorpheniramine",
  "모드콜콜드시럽":"Chlorpheniramine",
  "모드콜플루노즈건조시럽":"Chlorpheniramine",
  "모아노즈연질캡슐":"Chlorpheniramine",
  "모아코에이연질캡슐":"Chlorpheniramine",
  "모아코정":"Chlorpheniramine",
  "모아코프에이연질캡슐":"Chlorpheniramine",
  "모아코프연질캡슐":"Chlorpheniramine",
  "모아콜드에이연질캡슐":"Chlorpheniramine",
  "모아콜연질캡슐":"Chlorpheniramine",
  "모아쿨점안액":"Chlorpheniramine",
  "모아큐어점안액":"Chlorpheniramine",
  "목기천연질캡슐":"Chlorpheniramine",
  "무무키즈노즈시럽":"Chlorpheniramine",
  "무무키즈콜드시럽":"Chlorpheniramine",
  "물리나겔":"Chlorpheniramine",
  "물린더겔":"Chlorpheniramine",
  "뮤코에이시럽":"Chlorpheniramine",
  "뮤코코푸시럽":"Chlorpheniramine",
  "미놀노즈에스점비액":"Chlorpheniramine",
  "미리코프연질캡슐":"Chlorpheniramine",
  "미리코프파워연질캡슐":"Chlorpheniramine",
  "미리콜연질캡슐":"Chlorpheniramine",
  "미안블루점안액":"Chlorpheniramine",
  "미안케어점안액":"Chlorpheniramine",
  "바로온노즈연질캡슐":"Chlorpheniramine",
  "바로콜에프캡슐":"Chlorpheniramine",
  "바로쿨액":"Chlorpheniramine",
  "바스칼캡슐":"Chlorpheniramine",
  "바이콜시럽":"Chlorpheniramine",
  "방콜노즈시럽":"Chlorpheniramine",
  "방콜콜드시럽":"Chlorpheniramine",
  "뱅드롱액":"Chlorpheniramine",
  "벌모엔겔":"Chlorpheniramine",
  "벌무덴쿨겔":"Chlorpheniramine",
  "베노라민정":"Chlorpheniramine",
  "베비맥시럽":"Chlorpheniramine",
  "베아브론에이시럽":"Chlorpheniramine",
  "벤포코프연질캡슐":"Chlorpheniramine",
  "벤포콜드연질캡슐":"Chlorpheniramine",
  "벨노즈캡슐":"Chlorpheniramine",
  "보감탕노즈액":"Chlorpheniramine",
  "브라이점안액":"Chlorpheniramine",
  "브레노즈연질캡슐":"Chlorpheniramine",
  "브렌콜에프연질캡슐":"Chlorpheniramine",
  "브이코에이치캡슐":"Chlorpheniramine",
  "브이코엔연질캡슐":"Chlorpheniramine",
  "브이코프에이치캡슐":"Chlorpheniramine",
  "브이콜드시럽":"Chlorpheniramine",
  "브이콜드케이시럽":"Chlorpheniramine",
  "브이콜에이치캡슐":"Chlorpheniramine",
  "브이콜엔연질캡슐":"Chlorpheniramine",
  "비감수액":"Chlorpheniramine",
  "비비맥스연질캡슐":"Chlorpheniramine",
  "비비코에스연질캡슐":"Chlorpheniramine",
  "비스타에스점안액":"Chlorpheniramine",
  "비알코시럽":"Chlorpheniramine",
  "비알코에이시럽":"Chlorpheniramine",
  "비엠쿨에프캡슐":"Chlorpheniramine",
  "비콜연질캡슐":"Chlorpheniramine",
  "비쿨점비액":"Chlorpheniramine",
  "비타콜연질캡슐":"Chlorpheniramine",
  "비프리스트롱연질캡슐":"Chlorpheniramine",
  "뿌레콜에프캡슐":"Chlorpheniramine",
  "사포날과립":"Chlorpheniramine",
  "사포날에스과립":"Chlorpheniramine",
  "세나코시럽":"Chlorpheniramine",
  "세나쿨시럽":"Chlorpheniramine",
  "세네풀에스액":"Chlorpheniramine",
  "세리펙에스정":"Chlorpheniramine",
  "세브론에이시럽":"Chlorpheniramine",
  "세이브론캡슐":"Chlorpheniramine",
  "세코라시럽":"Chlorpheniramine",
  "세파콜에프캡슐":"Chlorpheniramine",
  "센티골드엠캡슐":"Chlorpheniramine",
  "센티골드캡슐":"Chlorpheniramine",
  "속콜시럽":"Chlorpheniramine",
  "속콜코프엘연질캡슐":"Chlorpheniramine",
  "속콜큐어캡슐":"Chlorpheniramine",
  "속콜플러스연질캡슐":"Chlorpheniramine",
  "솔루샷노즈연질캡슐":"Chlorpheniramine",
  "솔루샷쿨연질캡슐":"Chlorpheniramine",
  "솔트스틱액":"Chlorpheniramine",
  "솔트액":"Chlorpheniramine",
  "쉐러콜에스연질캡슐":"Chlorpheniramine",
  "슈페젠정":"Chlorpheniramine",
  "스노콜정":"Chlorpheniramine",
  "스완안약":"Chlorpheniramine",
  "스완타치":"Chlorpheniramine",
  "스파치올액":"Chlorpheniramine",
  "스피콜드연질캡슐":"Chlorpheniramine",
  "시노카엔캡슐":"Chlorpheniramine",
  "시노카엔플러스연질캡슐":"Chlorpheniramine",
  "시노피드플러스정":"Chlorpheniramine",
  "시스틴캡슐":"Chlorpheniramine",
  "시크린뷰점안액":"Chlorpheniramine",
  "시크린원점안액":"Chlorpheniramine",
  "신도톱쿨점안액":"Chlorpheniramine",
  "신신물파스에스":"Chlorpheniramine",
  "신코에프연질캡슐":"Chlorpheniramine",
  "신콜에프연질캡슐":"Chlorpheniramine",
  "신폴에이점안액":"Chlorpheniramine",
  "신한방화콜캡슐":"Chlorpheniramine",
  "실비도정":"Chlorpheniramine",
  "싹콜드정":"Chlorpheniramine",
  "쌍패원노즈액":"Chlorpheniramine",
  "쌩코에스연질캡슐":"Chlorpheniramine",
  "쌩코에이연질캡슐":"Chlorpheniramine",
  "쌩코연질캡슐":"Chlorpheniramine",
  "쌩코프에스연질캡슐":"Chlorpheniramine",
  "쌩코프에이연질캡슐":"Chlorpheniramine",
  "쌩코프연질캡슐":"Chlorpheniramine",
  "쌩콜에스연질캡슐":"Chlorpheniramine",
  "쌩콜에이연질캡슐":"Chlorpheniramine",
  "쌩콜연질캡슐":"Chlorpheniramine",
  "써스펜나이트정":"Chlorpheniramine",
  "써스펜데이정":"Chlorpheniramine",
  "쏙코에스연질캡슐":"Chlorpheniramine",
  "쏙코에이연질캡슐":"Chlorpheniramine",
  "쏙코에프연질캡슐":"Chlorpheniramine",
  "쏙콜에스연질캡슐":"Chlorpheniramine",
  "쏙콜에이연질캡슐":"Chlorpheniramine",
  "쏙콜에프연질캡슐":"Chlorpheniramine",
  "씨콜드노즈정":"Chlorpheniramine",
  "씨콜드정":"Chlorpheniramine",
  "씨콜드플러스노즈정":"Chlorpheniramine",
  "씨콜드플러스정":"Chlorpheniramine",
  "씨콜드플러스코프정":"Chlorpheniramine",
  "아나프리스프레이":"Chlorpheniramine",
  "아루진정":"Chlorpheniramine",
  "아모스겔":"Chlorpheniramine",
  "아무로스프레이":"Chlorpheniramine",
  "아미듀오시럽":"Chlorpheniramine",
  "아스마에프시럽":"Chlorpheniramine",
  "아웃콜목골드캡슐":"Chlorpheniramine",
  "아웃콜에프캡슐":"Chlorpheniramine",
  "아웃콜코정":"Chlorpheniramine",
  "아이뉴점안액":"Chlorpheniramine",
  "아이루비로즈점안액":"Chlorpheniramine",
  "아이미루40이엑스골드점안액":"Chlorpheniramine",
  "아이미루40이엑스마일드점안액":"Chlorpheniramine",
  "아이미루40이엑스점안액":"Chlorpheniramine",
  "아이봉더블유세안액":"Chlorpheniramine",
  "아이봉마일드세안액":"Chlorpheniramine",
  "아이봉씨세안액":"Chlorpheniramine",
  "아이봉쿨세안액":"Chlorpheniramine",
  "아이수점안액":"Chlorpheniramine",
  "아이케어점안액":"Chlorpheniramine",
  "아이클리어점안액":"Chlorpheniramine",
  "아이플블루점안액":"Chlorpheniramine",
  "아이플클리어점안액":"Chlorpheniramine",
  "아이필점안액":"Chlorpheniramine",
  "아인쿨점안액":"Chlorpheniramine",
  "아임파인콜드연질캡슐":"Chlorpheniramine",
  "아카쿨엠점안액":"Chlorpheniramine",
  "아토미겔":"Chlorpheniramine",
  "아포니카에어로솔":"Chlorpheniramine",
  "안티노에스정":"Chlorpheniramine",
  "안티노정":"Chlorpheniramine",
  "알레스탑에스정":"Chlorpheniramine",
  "알카펜네이잘연질캡슐":"Chlorpheniramine",
  "알파콜에프캡슐":"Chlorpheniramine",
  "암돌연질캡슐":"Chlorpheniramine",
  "액티브노즈연질캡슐":"Chlorpheniramine",
  "액티브콜드연질캡슐":"Chlorpheniramine",
  "에이노즈연질캡슐":"Chlorpheniramine",
  "에이치코연질캡슐":"Chlorpheniramine",
  "에이치콜연질캡슐":"Chlorpheniramine",
  "에이코프연질캡슐":"Chlorpheniramine",
  "에이콜연질캡슐":"Chlorpheniramine",
  "에취스에프연질캡슐":"Chlorpheniramine",
  "에치탑에스캡슐":"Chlorpheniramine",
  "에코리자정":"Chlorpheniramine",
  "에프노즈시럽":"Chlorpheniramine",
  "에프코프시럽":"Chlorpheniramine",
  "에프쿨시럽":"Chlorpheniramine",
  "엑센트라노즈연질캡슐":"Chlorpheniramine",
  "엑센트라콜드연질캡슐":"Chlorpheniramine",
  "엑스코프네오시럽":"Chlorpheniramine",
  "엑스코프에이연질캡슐":"Chlorpheniramine",
  "엑스코프연질캡슐":"Chlorpheniramine",
  "엑스콜노즈정":"Chlorpheniramine",
  "엑스콜콜드에프캡슐":"Chlorpheniramine",
  "엑스콜큐노즈시럽":"Chlorpheniramine",
  "엑스콜큐업콜드시럽":"Chlorpheniramine",
  "엑스콜큐콜드시럽":"Chlorpheniramine",
  "엑쎈코에스연질캡슐":"Chlorpheniramine",
  "엑쎈콜연질캡슐":"Chlorpheniramine",
  "엔디콜노즈정":"Chlorpheniramine",
  "엔비코프정":"Chlorpheniramine",
  "엔콜시럽":"Chlorpheniramine",
  "오라드린에프정":"Chlorpheniramine",
  "오로친에스정":"Chlorpheniramine",
  "오로친에프정":"Chlorpheniramine",
  "오메코에프정":"Chlorpheniramine",
  "오메코정":"Chlorpheniramine",
  "오메콜에프캡슐":"Chlorpheniramine",
  "오소플루노즈캡슐":"Chlorpheniramine",
  "오소플루오리엔스캡슐":"Chlorpheniramine",
  "오소플루콜드산":"Chlorpheniramine",
  "오소플루콜드캡슐":"Chlorpheniramine",
  "옥클리빈나잘스프레이":"Chlorpheniramine",
  "옴니콜연질캡슐":"Chlorpheniramine",
  "옴니콜코프연질캡슐":"Chlorpheniramine",
  "옵트클린점안액":"Chlorpheniramine",
  "옵티블루점안액":"Chlorpheniramine",
  "옵티큐어점안액":"Chlorpheniramine",
  "우노바캡슐":"Chlorpheniramine",
  "원쌍탕노즈액":"Chlorpheniramine",
  "원콜드노즈시럽":"Chlorpheniramine",
  "원콜드시럽":"Chlorpheniramine",
  "위드노즈연질캡슐":"Chlorpheniramine",
  "위드콜드연질캡슐":"Chlorpheniramine",
  "윈콜드연질캡슐":"Chlorpheniramine",
  "윈콜드연질캡슐":"Chlorpheniramine",
  "윈콜드코연질캡슐":"Chlorpheniramine",
  "유라민시럽":"Chlorpheniramine",
  "유메콜연질캡슐":"Chlorpheniramine",
  "이너노즈캡슐":"Chlorpheniramine",
  "이노코정":"Chlorpheniramine",
  "이노콜에이액":"Chlorpheniramine",
  "이노콜에프정":"Chlorpheniramine",
  "이노콜파워정":"Chlorpheniramine",
  "이노펜과립":"Chlorpheniramine",
  "이부캐치콜드연질캡슐":"Chlorpheniramine",
  "이부퀵노즈연질캡슐":"Chlorpheniramine",
  "이부퀵콜드연질캡슐":"Chlorpheniramine",
  "이지목플러스씨캡슐":"Chlorpheniramine",
  "이지콜드노즈연질캡슐":"Chlorpheniramine",
  "이지콜드플러스연질캡슐":"Chlorpheniramine",
  "이지콜씨플러스캡슐":"Chlorpheniramine",
  "이지트립시럽":"Chlorpheniramine",
  "일양투아이블루점안액":"Chlorpheniramine",
  "일양투아이케어점안액":"Chlorpheniramine",
  "제감노즈캡슐":"Chlorpheniramine",
  "제감콜드에스캡슐":"Chlorpheniramine",
  "제감콜드캡슐":"Chlorpheniramine",
  "제로코연질캡슐":"Chlorpheniramine",
  "제로코푸시럽":"Chlorpheniramine",
  "제로코프연질캡슐":"Chlorpheniramine",
  "제로콜연질캡슐":"Chlorpheniramine",
  "제이비케이콜캡슐":"Chlorpheniramine",
  "지민에스정":"Chlorpheniramine",
  "진탁콜캡슐":"Chlorpheniramine",
  "챔프노즈시럽":"Chlorpheniramine",
  "챔프콜드시럽":"Chlorpheniramine",
  "챔프콜드펜시럽":"Chlorpheniramine",
  "챔프콜드펜하이시럽":"Chlorpheniramine",
  "청나점안액":"Chlorpheniramine",
  "초감콜쓰리정":"Chlorpheniramine",
  "츄츄노즈연질캡슐":"Chlorpheniramine",
  "치감노즈액":"Chlorpheniramine",
  "카밀레쿨점안액":"Chlorpheniramine",
  "캐롤비코프연질캡슐":"Chlorpheniramine",
  "캐롤비코프플러스연질캡슐":"Chlorpheniramine",
  "캐롤비콜드연질캡슐":"Chlorpheniramine",
  "캐롤비콜드플러스연질캡슐":"Chlorpheniramine",
  "캐롤키즈노즈시럽":"Chlorpheniramine",
  "캐롤키즈콜드시럽":"Chlorpheniramine",
  "캐치코프정":"Chlorpheniramine",
  "캐치콜에스연질캡슐":"Chlorpheniramine",
  "케이콜드시럽":"Chlorpheniramine",
  "케이콜드키즈시럽":"Chlorpheniramine",
  "케이파이콜싹과립":"Chlorpheniramine",
  "코감노즈정":"Chlorpheniramine",
  "코감콜캡슐":"Chlorpheniramine",
  "코다나에스시럽":"Chlorpheniramine",
  "코다나플러스정":"Chlorpheniramine",
  "코담시럽":"Chlorpheniramine",
  "코대원에스시럽":"Chlorpheniramine",
  "코대원정":"Chlorpheniramine",
  "코대원포르테시럽":"Chlorpheniramine",
  "코대원플러스정":"Chlorpheniramine",
  "코데날시럽":"Chlorpheniramine",
  "코데날액":"Chlorpheniramine",
  "코데날정":"Chlorpheniramine",
  "코데농정":"Chlorpheniramine",
  "코데닝시럽":"Chlorpheniramine",
  "코데닝정":"Chlorpheniramine",
  "코덴스정":"Chlorpheniramine",
  "코드렌연질캡슐":"Chlorpheniramine",
  "코디캄에스시럽":"Chlorpheniramine",
  "코디프로시럽":"Chlorpheniramine",
  "코뚜에스시럽":"Chlorpheniramine",
  "코뚜에프시럽":"Chlorpheniramine",
  "코르텍골드구강붕해필름":"Chlorpheniramine",
  "코리투살노즈시럽":"Chlorpheniramine",
  "코리투살에스노즈연질캡슐":"Chlorpheniramine",
  "코리투살에스콜드연질캡슐":"Chlorpheniramine",
  "코리투살에프콜드시럽":"Chlorpheniramine",
  "코린시럽":"Chlorpheniramine",
  "코린투비정":"Chlorpheniramine",
  "코린투에스정":"Chlorpheniramine",
  "코마키텐나잘스프레이":"Chlorpheniramine",
  "코마키텐큐나잘스프레이":"Chlorpheniramine",
  "코만코정":"Chlorpheniramine",
  "코메키나스프레이":"Chlorpheniramine",
  "코미시럽":"Chlorpheniramine",
  "코미업시럽":"Chlorpheniramine",
  "코미정":"Chlorpheniramine",
  "코미코프시럽":"Chlorpheniramine",
  "코벤시럽":"Chlorpheniramine",
  "코비안에스시럽":"Chlorpheniramine",
  "코비안에스정":"Chlorpheniramine",
  "코스노즈연질캡슐":"Chlorpheniramine",
  "코스콜드연질캡슐":"Chlorpheniramine",
  "코애드에프정":"Chlorpheniramine",
  "코애드정":"Chlorpheniramine",
  "코앤코정":"Chlorpheniramine",
  "코앤쿨나잘스프레이":"Chlorpheniramine",
  "코앤쿨에스나잘스프레이":"Chlorpheniramine",
  "코엔드에프캡슐":"Chlorpheniramine",
  "코잘프로나잘스프레이액":"Chlorpheniramine",
  "코코스탑나잘스프레이":"Chlorpheniramine",
  "코크린정":"Chlorpheniramine",
  "코투루텐나잘스프레이":"Chlorpheniramine",
  "코페민연질캡슐":"Chlorpheniramine",
  "코포나시럽":"Chlorpheniramine",
  "코포나시럽에스":"Chlorpheniramine",
  "코푸스탑플러스연질캡슐":"Chlorpheniramine",
  "코푸시럽":"Chlorpheniramine",
  "코푸시럽에스":"Chlorpheniramine",
  "코푸엔에스시럽":"Chlorpheniramine",
  "코푸정":"Chlorpheniramine",
  "코푸정에스":"Chlorpheniramine",
  "코푸진시럽":"Chlorpheniramine",
  "코푸콜드에스액":"Chlorpheniramine",
  "코프엔드정":"Chlorpheniramine",
  "코프원시럽":"Chlorpheniramine",
  "코프패스연질캡슐":"Chlorpheniramine",
  "콘택콜드캡슐":"Chlorpheniramine",
  "콜그린에이캡슐":"Chlorpheniramine",
  "콜대원노즈에스시럽":"Chlorpheniramine",
  "콜대원노즈큐에스시럽":"Chlorpheniramine",
  "콜대원코나에스나잘스프레이액":"Chlorpheniramine",
  "콜대원콜드시럽":"Chlorpheniramine",
  "콜대원콜드에스시럽":"Chlorpheniramine",
  "콜대원콜드큐시럽":"Chlorpheniramine",
  "콜대원키즈노즈시럽":"Chlorpheniramine",
  "콜대원키즈노즈에스시럽":"Chlorpheniramine",
  "콜대원키즈콜드시럽":"Chlorpheniramine",
  "콜대원키즈콜드에스시럽":"Chlorpheniramine",
  "콜드디앤엔연질캡슐":"Chlorpheniramine",
  "콜드바로정":"Chlorpheniramine",
  "콜드브레이크캡슐":"Chlorpheniramine",
  "콜드샷시럽":"Chlorpheniramine",
  "콜드엔정":"Chlorpheniramine",
  "콜드큐정":"Chlorpheniramine",
  "콜드팡시럽":"Chlorpheniramine",
  "콜드프로펜노즈연질캡슐":"Chlorpheniramine",
  "콜드프로펜연질캡슐":"Chlorpheniramine",
  "콜드플러스캡슐":"Chlorpheniramine",
  "콜디에스시럽":"Chlorpheniramine",
  "콜락연질캡슐":"Chlorpheniramine",
  "콜로브론캡슐":"Chlorpheniramine",
  "콜록노즈연질캡슐":"Chlorpheniramine",
  "콜록종합연질캡슐":"Chlorpheniramine",
  "콜록콜드시럽":"Chlorpheniramine",
  "콜록프로노즈연질캡슐":"Chlorpheniramine",
  "콜록프로종합연질캡슐":"Chlorpheniramine",
  "콜맥노즈시럽":"Chlorpheniramine",
  "콜맥에스시럽":"Chlorpheniramine",
  "콜맥콜드시럽":"Chlorpheniramine",
  "콜민노즈연질캡슐":"Chlorpheniramine",
  "콜민에스시럽":"Chlorpheniramine",
  "콜민에스정":"Chlorpheniramine",
  "콜민에이시럽":"Chlorpheniramine",
  "콜민에이정":"Chlorpheniramine",
  "콜민코연질캡슐":"Chlorpheniramine",
  "콜민콜드연질캡슐":"Chlorpheniramine",
  "콜바스타에프정":"Chlorpheniramine",
  "콜브론에이시럽":"Chlorpheniramine",
  "콜스탑연질캡슐":"Chlorpheniramine",
  "콜쓰리시럽":"Chlorpheniramine",
  "콜앤비타에프캡슐":"Chlorpheniramine",
  "콜제로연질캡슐":"Chlorpheniramine",
  "콜즈록나잘스프레이":"Chlorpheniramine",
  "콜콜에스캡슐":"Chlorpheniramine",
  "콜콜콜드연질캡슐":"Chlorpheniramine",
  "콜콜펜시럽":"Chlorpheniramine",
  "콜키퍼시럽":"Chlorpheniramine",
  "콜키퍼키즈시럽":"Chlorpheniramine",
  "콜투윈캡슐":"Chlorpheniramine",
  "콜핀정":"Chlorpheniramine",
  "콤비올에이정":"Chlorpheniramine",
  "쿨럭노즈시럽":"Chlorpheniramine",
  "쿨럭콜드시럽":"Chlorpheniramine",
  "퀵코연질캡슐":"Chlorpheniramine",
  "퀵코플러스정":"Chlorpheniramine",
  "퀵플러스연질캡슐":"Chlorpheniramine",
  "큐어기가연질캡슐":"Chlorpheniramine",
  "큐어코연질캡슐":"Chlorpheniramine",
  "큐어코프에이연질캡슐":"Chlorpheniramine",
  "큐어코프플러스연질캡슐":"Chlorpheniramine",
  "큐어코플러스연질캡슐":"Chlorpheniramine",
  "큐어콜연질캡슐":"Chlorpheniramine",
  "큐어콜플러스연질캡슐":"Chlorpheniramine",
  "크린코정":"Chlorpheniramine",
  "클로르에이시럽":"Chlorpheniramine",
  "클로안에스큐점안액":"Chlorpheniramine",
  "클린톡톡비나잘스프레이":"Chlorpheniramine",
  "클린파워연질캡슐":"Chlorpheniramine",
  "키드고액":"Chlorpheniramine",
  "킥노즈에스연질캡슐":"Chlorpheniramine",
  "킥노즈에프연질캡슐":"Chlorpheniramine",
  "킥콜드에스연질캡슐":"Chlorpheniramine",
  "킥콜연질캡슐":"Chlorpheniramine",
  "타세놀콜드시럽":"Chlorpheniramine",
  "타세놀콜드캡슐":"Chlorpheniramine",
  "타이레놀콜드에스정":"Chlorpheniramine",
  "테보민정":"Chlorpheniramine",
  "토탈노즈플루연질캡슐":"Chlorpheniramine",
  "토탈플루연질캡슐":"Chlorpheniramine",
  "톡아야산":"Chlorpheniramine",
  "톡콜드산":"Chlorpheniramine",
  "톡콜콜산":"Chlorpheniramine",
  "투윈에취시럽":"Chlorpheniramine",
  "투콜캡슐":"Chlorpheniramine",
  "툭툭콜드연질캡슐":"Chlorpheniramine",
  "툭툭플러스콜드연질캡슐":"Chlorpheniramine",
  "트레코정":"Chlorpheniramine",
  "티나청포르테점안액":"Chlorpheniramine",
  "티나케어점안액":"Chlorpheniramine",
  "티엔코연질캡슐":"Chlorpheniramine",
  "티엔콜연질캡슐":"Chlorpheniramine",
  "틴클점안액":"Chlorpheniramine",
  "파뚜루정":"Chlorpheniramine",
  "파워콜노즈연질캡슐":"Chlorpheniramine",
  "파워콜노즈큐연질캡슐":"Chlorpheniramine",
  "파워콜에스연질캡슐":"Chlorpheniramine",
  "파워콜캡슐":"Chlorpheniramine",
  "파이에온정":"Chlorpheniramine",
  "파인콜노즈시럽":"Chlorpheniramine",
  "파인콜정":"Chlorpheniramine",
  "파인콜콜드시럽":"Chlorpheniramine",
  "판콜에스내복액":"Chlorpheniramine",
  "판콜에이내복액":"Chlorpheniramine",
  "판콜케어내복액":"Chlorpheniramine",
  "판텍에이액":"Chlorpheniramine",
  "판텍에이정":"Chlorpheniramine",
  "판텍콜드시럽":"Chlorpheniramine",
  "판텍큐코프플러스연질캡슐":"Chlorpheniramine",
  "판텍타임산제":"Chlorpheniramine",
  "판텍타임콜드시럽":"Chlorpheniramine",
  "판토에이내복액":"Chlorpheniramine",
  "판피린씨액":"Chlorpheniramine",
  "판피린알파정":"Chlorpheniramine",
  "판피린에이액":"Chlorpheniramine",
  "판피린큐액":"Chlorpheniramine",
  "판피린큐콜드액":"Chlorpheniramine",
  "판피린타임데이플루건조시럽":"Chlorpheniramine",
  "판피린타임산제":"Chlorpheniramine",
  "판피린타임이부노즈시럽":"Chlorpheniramine",
  "판피린타임이부콜드시럽":"Chlorpheniramine",
  "판피린티정":"Chlorpheniramine",
  "퍼슨콜샷에프시럽":"Chlorpheniramine",
  "페니라민정":"Chlorpheniramine",
  "페니라민주사":"Chlorpheniramine",
  "페닐주":"Chlorpheniramine",
  "페리나정":"Chlorpheniramine",
  "페브로민에이시럽":"Chlorpheniramine",
  "페이지연질캡슐":"Chlorpheniramine",
  "포린정":"Chlorpheniramine",
  "푸로콜에이캡슐":"Chlorpheniramine",
  "푸록토케어스프레액":"Chlorpheniramine",
  "푸르코프연질캡슐":"Chlorpheniramine",
  "푸르콜드연질캡슐":"Chlorpheniramine",
  "푸푸에프연질캡슐":"Chlorpheniramine",
  "프레시뷰베타점안액":"Chlorpheniramine",
  "프리노즈에스정":"Chlorpheniramine",
  "프리노즈정":"Chlorpheniramine",
  "플루콜캡슐":"Chlorpheniramine",
  "하드콜연질캡슐":"Chlorpheniramine",
  "하디코정":"Chlorpheniramine",
  "하디코플러스정":"Chlorpheniramine",
  "하디콜맥스정":"Chlorpheniramine",
  "하디콜에스연질캡슐":"Chlorpheniramine",
  "하디콜정":"Chlorpheniramine",
  "하디콜큐정":"Chlorpheniramine",
  "하디큐콜드연질캡슐":"Chlorpheniramine",
  "하벤목에스캡슐":"Chlorpheniramine",
  "하벤에스액":"Chlorpheniramine",
  "하벤유에스캡슐":"Chlorpheniramine",
  "하벤코정":"Chlorpheniramine",
  "하벤코프에스액":"Chlorpheniramine",
  "하벤콜에스액":"Chlorpheniramine",
  "하벤콜큐연질캡슐":"Chlorpheniramine",
  "하벤큐연질캡슐":"Chlorpheniramine",
  "하벤키즈시럽":"Chlorpheniramine",
  "하벤파워골드캡슐":"Chlorpheniramine",
  "하벤파워에스캡슐":"Chlorpheniramine",
  "하벤플러스나잘스프레이":"Chlorpheniramine",
  "하벤허브골드캡슐":"Chlorpheniramine",
  "하벤허브에프캡슐":"Chlorpheniramine",
  "하이눈점안액":"Chlorpheniramine",
  "하이소밍정":"Chlorpheniramine",
  "한신노콜액":"Chlorpheniramine",
  "한신노콜에스액":"Chlorpheniramine",
  "한신노콜캡슐":"Chlorpheniramine",
  "한신한스콜에스캡슐":"Chlorpheniramine",
  "한풍노즈액":"Chlorpheniramine",
  "한풍코프액":"Chlorpheniramine",
  "한풍콜드액":"Chlorpheniramine",
  "해소민에스캡슐":"Chlorpheniramine",
  "해소코푸에스시럽":"Chlorpheniramine",
  "현대물파스에프":"Chlorpheniramine",
  "화이투벤노즈시럽":"Chlorpheniramine",
  "화이투벤씨플러스캡슐":"Chlorpheniramine",
  "화이투벤콜드시럽":"Chlorpheniramine",
  "화인코프에이캡슐":"Chlorpheniramine",
  "화콜노즈정":"Chlorpheniramine",
  "화콜정":"Chlorpheniramine",
  "화콜클래식원연질캡슐":"Chlorpheniramine",
  "화콜키즈콜드시럽":"Chlorpheniramine",
  "후리코정":"Chlorpheniramine",
  "휴엔솔노즈연질캡슐":"Chlorpheniramine",
  "휴온스클로르페니라민말레산염주사액":"Chlorpheniramine",
  "명인클로르프로마진염산염정":"Chlorpromazine",
  "네오마찐정":"Chlorpromazine",
  "알피트주사":"Cimetropium",
  "알피움정":"Cimetropium",
  "브로퓸주사":"Cimetropium",
  "시메트로주사":"Cimetropium",
  "마스질정":"Clemastine",
  "그로민캡슐":"Clomipramine",
  "환인염산클로미프라민캡슐":"Clomipramine",
  "클로잭정":"Clomipramine",
  "네노마정":"Clomipramine",
  "컨덴시아정":"Clomipramine",
  "원투정":"Clomipramine",
  "구세정":"Clomipramine",
  "클로자릴정":"Clozapine",
  "클자핀정":"Clozapine",
  "삐삐콜플러스정":"Dexbrompheniramine",
  "르텍골드구강붕해필름":"Dexchlorpheniramine",
  "노즈퀵구강용해필름":"Dexchlorpheniramine",
  "스토베린정":"Dicyclomine(dicycloverine)",
  "스파로민정":"Dicyclomine(dicycloverine)",
  "스파메드정":"Dicyclomine(dicycloverine)",
  "스파토민캡슐":"Dicyclomine(dicycloverine)",
  "시클로베린정":"Dicyclomine(dicycloverine)",
  "신신파파베정":"Dicyclomine(dicycloverine)",
  "싸이라민정":"Dicyclomine(dicycloverine)",
  "싸이베린정":"Dicyclomine(dicycloverine)",
  "쑥베린정":"Dicyclomine(dicycloverine)",
  "아나파베정":"Dicyclomine(dicycloverine)",
  "아네린정":"Dicyclomine(dicycloverine)",
  "아파베린정":"Dicyclomine(dicycloverine)",
  "안티베린정":"Dicyclomine(dicycloverine)",
  "에스코판정":"Dicyclomine(dicycloverine)",
  "이너베린정":"Dicyclomine(dicycloverine)",
  "이지정":"Dicyclomine(dicycloverine)",
  "제일파네린정":"Dicyclomine(dicycloverine)",
  "클로베린정":"Dicyclomine(dicycloverine)",
  "파베린정":"Dicyclomine(dicycloverine)",
  "나들이시럽":"Dimenhydrinate",
  "내안정":"Dimenhydrinate",
  "노벌티정":"Dimenhydrinate",
  "디노타시럽":"Dimenhydrinate",
  "디멘정":"Dimenhydrinate",
  "디카엠정":"Dimenhydrinate",
  "마레오키즈시럽":"Dimenhydrinate",
  "마미즈시럽":"Dimenhydrinate",
  "멀리가때액":"Dimenhydrinate",
  "멀리가시럽":"Dimenhydrinate",
  "메카인큐액":"Dimenhydrinate",
  "무빙스탑츄어블정":"Dimenhydrinate",
  "뱅드롱에스시럽":"Dimenhydrinate",
  "보나링스피드액":"Dimenhydrinate",
  "보나링에이정":"Dimenhydrinate",
  "보나링츄어블정":"Dimenhydrinate",
  "소보민시럽":"Dimenhydrinate",
  "스토멀산":"Dimenhydrinate",
  "스피롱액":"Dimenhydrinate",
  "씨엠지씽씽시럽":"Dimenhydrinate",
  "알레버트정":"Dimenhydrinate",
  "어지논앤액":"Dimenhydrinate",
  "에르버트정":"Dimenhydrinate",
  "오네론액":"Dimenhydrinate",
  "이지고시럽":"Dimenhydrinate",
  "이지롱내복액":"Dimenhydrinate",
  "이지롱플러스액":"Dimenhydrinate",
  "조은아이부릉시럽":"Dimenhydrinate",
  "차배비시럽":"Dimenhydrinate",
  "차배비플러스시럽":"Dimenhydrinate",
  "차잘타액":"Dimenhydrinate",
  "카메드정":"Dimenhydrinate",
  "코지롱액":"Dimenhydrinate",
  "키미테정":"Dimenhydrinate",
  "타고가고액":"Dimenhydrinate",
  "토스롱액":"Dimenhydrinate",
  "토스롱에스액":"Dimenhydrinate",
  "톡트립산":"Dimenhydrinate",
  "프리고시럽":"Dimenhydrinate",
  "해피트립액":"Dimenhydrinate",
  "가두벌크림":"Diphenhydramine",
  "그린솔트에프액":"Diphenhydramine",
  "그린쏘인겔":"Diphenhydramine",
  "그린쏘인디겔":"Diphenhydramine",
  "그밤엔연질캡슐":"Diphenhydramine",
  "노펜미니플라스타":"Diphenhydramine",
  "녹십자제놀마일드핫트카타플라스마":"Diphenhydramine",
  "녹십자제놀카타플라스마":"Diphenhydramine",
  "누보클렌액":"Diphenhydramine",
  "다펜나이트연질캡슐":"Diphenhydramine",
  "단자민정":"Diphenhydramine",
  "더마스킨연고":"Diphenhydramine",
  "더마큐연고":"Diphenhydramine",
  "더모메디큐액":"Diphenhydramine",
  "동전핫파스플라스타":"Diphenhydramine",
  "두두엔액":"Diphenhydramine",
  "두피나액":"Diphenhydramine",
  "둥근머리버물리겔":"Diphenhydramine",
  "둥근머리버물리에스겔":"Diphenhydramine",
  "드림굿연질캡슐":"Diphenhydramine",
  "디큐펜프로나이트연질캡슐":"Diphenhydramine",
  "디투인비정":"Diphenhydramine",
  "디판버그겔":"Diphenhydramine",
  "디펙타민연질캡슐":"Diphenhydramine",
  "디펜동전플라스타(원지름28mm)":"Diphenhydramine",
  "딥슬링연질캡슐":"Diphenhydramine",
  "래피콜데이앤나잇연질캡슐":"Diphenhydramine",
  "레스타민코와파우더크림":"Diphenhydramine",
  "리카에이크림":"Diphenhydramine",
  "마미송에프크림":"Diphenhydramine",
  "맥콜드시럽":"Diphenhydramine",
  "멘소래담에이디크림":"Diphenhydramine",
  "멘소래담코인플라스타":"Diphenhydramine",
  "멜로콤정":"Diphenhydramine",
  "모드콜플루나이트건조시럽":"Diphenhydramine",
  "모물린키드크림":"Diphenhydramine",
  "모벌디액":"Diphenhydramine",
  "모비트롤겔":"Diphenhydramine",
  "모스쿨액":"Diphenhydramine",
  "모스쿨키드크림":"Diphenhydramine",
  "모키쿨플라스타":"Diphenhydramine",
  "무조날파워스프레이액":"Diphenhydramine",
  "무조무알파에어로솔":"Diphenhydramine",
  "무조무플러스겔":"Diphenhydramine",
  "물드라민에스겔":"Diphenhydramine",
  "물린디액":"Diphenhydramine",
  "물린디쿨액":"Diphenhydramine",
  "물린디키드크림":"Diphenhydramine",
  "물린디플라스타":"Diphenhydramine",
  "물린쿨겔":"Diphenhydramine",
  "물린쿨에스겔":"Diphenhydramine",
  "물린쿨에프겔":"Diphenhydramine",
  "미키크림":"Diphenhydramine",
  "바르민액":"Diphenhydramine",
  "바르지오모두크림":"Diphenhydramine",
  "버래물액":"Diphenhydramine",
  "버물리알파액":"Diphenhydramine",
  "버물리에스액":"Diphenhydramine",
  "버물리키드크림":"Diphenhydramine",
  "버물리플라스타":"Diphenhydramine",
  "버물리플러스액":"Diphenhydramine",
  "벌무덴리니멘트":"Diphenhydramine",
  "벌키퍼크림":"Diphenhydramine",
  "베노쿨에스액":"Diphenhydramine",
  "베노쿨키드크림":"Diphenhydramine",
  "베노터치힐러플라스타":"Diphenhydramine",
  "벨라에스정":"Diphenhydramine",
  "브로달정":"Diphenhydramine",
  "브로에스정":"Diphenhydramine",
  "비오플라스타":"Diphenhydramine",
  "세린드연고":"Diphenhydramine",
  "스리핀에스정":"Diphenhydramine",
  "스리핀정":"Diphenhydramine",
  "스킨앤쿨액":"Diphenhydramine",
  "슬리펠정":"Diphenhydramine",
  "시노코프캡슐":"Diphenhydramine",
  "신신냉파프카타플라스마":"Diphenhydramine",
  "신신미니핫플라스타":"Diphenhydramine",
  "신신파스에스":"Diphenhydramine",
  "써버쿨겔":"Diphenhydramine",
  "써버쿨액":"Diphenhydramine",
  "써버쿨에스액":"Diphenhydramine",
  "써버쿨이지겔":"Diphenhydramine",
  "써버쿨키드크림":"Diphenhydramine",
  "써버쿨플라스타":"Diphenhydramine",
  "써스펜나이트시럽":"Diphenhydramine",
  "쎄레마일드연고":"Diphenhydramine",
  "씨콜드나이트정":"Diphenhydramine",
  "씨콜드프리미엄정":"Diphenhydramine",
  "아웃가드겔":"Diphenhydramine",
  "안티센크림":"Diphenhydramine",
  "안티푸라민코인플라스타(원지름 28mm)":"Diphenhydramine",
  "애니클렌액":"Diphenhydramine",
  "에어신신파스":"Diphenhydramine",
  "엑스칠플러스연고":"Diphenhydramine",
  "오케이파워겔":"Diphenhydramine",
  "온큐플라스타":"Diphenhydramine",
  "유라케어로션":"Diphenhydramine",
  "유에츄데이앤나이트연질캡슐":"Diphenhydramine",
  "이밤이지연질캡슐":"Diphenhydramine",
  "이보드람연고":"Diphenhydramine",
  "이지엔6나이트연질캡슐":"Diphenhydramine",
  "이지퀼나잇액":"Diphenhydramine",
  "이치논크림":"Diphenhydramine",
  "이치레스큐플라스타":"Diphenhydramine",
  "제놀코인플라스타(원지름 28 mm)":"Diphenhydramine",
  "제놀쿨카타플라스마":"Diphenhydramine",
  "제로민연질캡슐":"Diphenhydramine",
  "제올라에스겔":"Diphenhydramine",
  "제올라에스액":"Diphenhydramine",
  "제올라에스플라스타":"Diphenhydramine",
  "제올라쿨겔":"Diphenhydramine",
  "제올라크림":"Diphenhydramine",
  "제일동전파프플라스타(원지름28mm)":"Diphenhydramine",
  "제일소프트핫카타플라스마":"Diphenhydramine",
  "제일쿨키드크림":"Diphenhydramine",
  "제일쿨텍카타플라스마":"Diphenhydramine",
  "조아포인트플라스타(원지름 28mm)":"Diphenhydramine",
  "졸리민정":"Diphenhydramine",
  "종근당공파스플라스타(원지름 28mm)":"Diphenhydramine",
  "치앤샷연고":"Diphenhydramine",
  "치치엔마일드크림":"Diphenhydramine",
  "칠드크림":"Diphenhydramine",
  "캐롤나이트연질캡슐":"Diphenhydramine",
  "캐롤나이트정":"Diphenhydramine",
  "코니자오디정":"Diphenhydramine",
  "코자미연질캡슐":"Diphenhydramine",
  "콜감나이트연질캡슐":"Diphenhydramine",
  "콜드윈시럽":"Diphenhydramine",
  "쿨드림연질캡슐":"Diphenhydramine",
  "쿨시드크림":"Diphenhydramine",
  "쿨키드크림":"Diphenhydramine",
  "클리마일드연고":"Diphenhydramine",
  "터비뉴더블액션겔":"Diphenhydramine",
  "터비뉴더블액션에어로솔":"Diphenhydramine",
  "터치쿨리니멘트":"Diphenhydramine",
  "테라플루콜드앤코프나이트타임건조시럽":"Diphenhydramine",
  "토비에스크림":"Diphenhydramine",
  "트인엔연고":"Diphenhydramine",
  "티어실에어로솔":"Diphenhydramine",
  "티타노에이연고":"Diphenhydramine",
  "파인디카정":"Diphenhydramine",
  "파인에스정":"Diphenhydramine",
  "판콜아이콜드시럽":"Diphenhydramine",
  "판콜에이치건조시럽":"Diphenhydramine",
  "판텍콜드시럽":"Diphenhydramine",
  "판텍타임건조시럽":"Diphenhydramine",
  "판텍타임나이트시럽":"Diphenhydramine",
  "판피린나이트액":"Diphenhydramine",
  "판피린타임나이트플루건조시럽":"Diphenhydramine",
  "펜잘나이트정":"Diphenhydramine",
  "푸리덴연고":"Diphenhydramine",
  "풋원겔":"Diphenhydramine",
  "프리치크림":"Diphenhydramine",
  "피엠쿨에어로솔":"Diphenhydramine",
  "하니동전파스플라스타":"Diphenhydramine",
  "한풍제통고온혈플라스타":"Diphenhydramine",
  "해피홈힐러플라스타":"Diphenhydramine",
  "헤모힐연고":"Diphenhydramine",
  "후치로연고":"Diphenhydramine",
  "사일레노정":"Doxepin",
  "명세핀정":"Doxepin",
  "사일원정":"Doxepin",
  "파마독세핀정":"Doxepin",
  "디너지아장용정":"Doxylamine",
  "디클렉틴장용정":"Doxylamine",
  "마미렉틴장용정":"Doxylamine",
  "스메르정":"Doxylamine",
  "아론정":"Doxylamine",
  "아졸정":"Doxylamine",
  "이지모닝장용정":"Doxylamine",
  "자멘쏙정":"Doxylamine",
  "자모다정":"Doxylamine",
  "자미슬정":"Doxylamine",
  "자비론정":"Doxylamine",
  "콜대원나이트시럽":"Doxylamine",
  "파렌스장용정":"Doxylamine",
  "포린피아정":"Doxylamine",
  "프리렉틴장용정":"Doxylamine",
  "토비애즈서방정":"Fesoterodine",
  "제일스파게린정":"Flavoxate",
  "유리락스시럽":"Hydroxyzine",
  "아디팜정":"Hydroxyzine",
  "두드리진시럽":"Hydroxyzine",
  "이치리진시럽":"Hydroxyzine",
  "유리토스정":"Imidafenacin",
  "명인이미프라민염산염정":"Imipramine",
  "환인이미프라민염산염정":"Imipramine",
  "노보민시럽":"Meclizine",
  "레디고액":"Meclizine",
  "멀스토구강용해필름":"Meclizine",
  "메카인정":"Meclizine",
  "메클린구강용해필름":"Meclizine",
  "뱅드롱액":"Meclizine",
  "보미롱산":"Meclizine",
  "엠클리진정":"Meclizine",
  "트라밍엔정":"Meclizine",
  "파비스염산메클리진정":"Meclizine",
  "파인탈에프츄어블정":"Meclizine",
  "노즈벨정":"Mequitazine",
  "노즈팡정":"Mequitazine",
  "바이넥스비타진정":"Mequitazine",
  "비엠쿨에스캡슐":"Mequitazine",
  "소아용프리마란시럽":"Mequitazine",
  "알레노즈캡슐":"Mequitazine",
  "액티플루노즈캡슐":"Mequitazine",
  "엔디콜노즈정":"Mequitazine",
  "코메키나캡슐":"Mequitazine",
  "코시원에스캡슐":"Mequitazine",
  "코시원큐캡슐":"Mequitazine",
  "코코엔캡슐":"Mequitazine",
  "코트리나캡슐":"Mequitazine",
  "코프리정":"Mequitazine",
  "콜드노즈싹정":"Mequitazine",
  "프리마란정":"Mequitazine",
  "센시발정":"Nortriptyline",
  "마티란정":"Octylonium bromide",
  "메가옥티로정":"Octylonium bromide",
  "메나스정":"Octylonium bromide",
  "메녹틸정":"Octylonium bromide",
  "메로늄정":"Octylonium bromide",
  "메틸로정":"Octylonium bromide",
  "모디피정":"Octylonium bromide",
  "베로틸정":"Octylonium bromide",
  "브로목틸정":"Octylonium bromide",
  "브목스정":"Octylonium bromide",
  "삼성옥틸로늄정":"Octylonium bromide",
  "셀릭스옥티늄정":"Octylonium bromide",
  "신일옥틸로늄브롬화물정":"Octylonium bromide",
  "에스녹틸정":"Octylonium bromide",
  "오녹틴정":"Octylonium bromide",
  "오테란정":"Octylonium bromide",
  "옥시린정":"Octylonium bromide",
  "옥티늄정":"Octylonium bromide",
  "옥티란정":"Octylonium bromide",
  "옥티로늄정":"Octylonium bromide",
  "옥틸로엠정":"Octylonium bromide",
  "옥틸론정":"Octylonium bromide",
  "옥틸정":"Octylonium bromide",
  "옥파짐정":"Octylonium bromide",
  "유가인정":"Octylonium bromide",
  "티브롱정":"Octylonium bromide",
  "푸로페날정":"Octylonium bromide",
  "뉴로자핀정":"Olanzapine",
  "산도스올란자핀정":"Olanzapine",
  "에이프렉사정":"Olanzapine",
  "영진올란자핀정":"Olanzapine",
  "올라핀정":"Olanzapine",
  "올자펙스정":"Olanzapine",
  "올자핀정":"Olanzapine",
  "자이레핀정":"Olanzapine",
  "자이자핀정":"Olanzapine",
  "자이프렉사자이디스확산정":"Olanzapine",
  "자이프렉사정":"Olanzapine",
  "자이피스오디정":"Olanzapine",
  "테바올란자핀정":"Olanzapine",
  "피엠에스올란자핀정":"Olanzapine",
  "스락신정":"Orphenadrine",
  "스코드린정":"Orphenadrine",
  "오페나딘서방정":"Orphenadrine",
  "오페릴50서방정":"Orphenadrine",
  "올페드린정":"Orphenadrine",
  "테리락스엑스엘서방정":"Orphenadrine",
  "파라게직정":"Orphenadrine",
  "동화디트로판정":"Oxybutynin",
  "나조린점안액":"Pheniramine",
  "테라플루테라플루나이트타임건조시럽":"Pheniramine",
  "트인비액":"Pheniramine",
  "프라미날주사":"Pridinol",
  "메시란주":"Pridinol",
  "콘락스주사액":"Pridinol",
  "콘락스정":"Pridinol",
  "메디놀주사액":"Pridinol",
  "푸락스주":"Pridinol",
  "프리메디주":"Pridinol",
  "프로이머정":"Procyclidine",
  "파로마정":"Procyclidine",
  "영프로마정":"Procyclidine",
  "파마프로시클리딘정":"Procyclidine",
  "글로베린정":"Propiverine",
  "글로베린정":"Propiverine",
  "넥스베린정":"Propiverine",
  "넥스베린정":"Propiverine",
  "대웅바이오프로피베린정":"Propiverine",
  "대웅바이오프로피베린정":"Propiverine",
  "디트루베린정":"Propiverine",
  "디트루베린정":"Propiverine",
  "베아베린정":"Propiverine",
  "베아베린정":"Propiverine",
  "비유프로정":"Propiverine",
  "비유피4정":"Propiverine",
  "비프로정":"Propiverine",
  "삼성프로피베린정":"Propiverine",
  "엔피베린정":"Propiverine",
  "유로나정":"Propiverine",
  "유로베린정":"Propiverine",
  "유로콘정":"Propiverine",
  "유로프로정":"Propiverine",
  "유로픽스정":"Propiverine",
  "유리베린정":"Propiverine",
  "유베린정":"Propiverine",
  "유프베린정":"Propiverine",
  "유피베린정":"Propiverine",
  "이연프로피베린정":"Propiverine",
  "큐어베린정":"Propiverine",
  "포베린정":"Propiverine",
  "프로베린정":"Propiverine",
  "프로베정":"Propiverine",
  "프로베픽스정":"Propiverine",
  "프로빈정":"Propiverine",
  "프로시톨정":"Propiverine",
  "프로피정":"Propiverine",
  "프롭정":"Propiverine",
  "휴피베린정":"Propiverine",
  "멘자펜정":"Pyrilamine(mepiramine)",
  "노량캡슐":"Scopolamine",
  "디페라민정":"Scopolamine",
  "멀리가때액":"Scopolamine",
  "메카인정":"Scopolamine",
  "메카인큐액":"Scopolamine",
  "무빙스탑츄어블정":"Scopolamine",
  "무스판정":"Scopolamine",
  "바로쿨액":"Scopolamine",
  "보나링스피드액":"Scopolamine",
  "보나링츄어블정":"Scopolamine",
  "보미롱산":"Scopolamine",
  "부스코판당의정":"Scopolamine",
  "부스코판플러스정":"Scopolamine",
  "샤이닝정":"Scopolamine",
  "스카이정":"Scopolamine",
  "스피드퀸정":"Scopolamine",
  "신신이지모션정":"Scopolamine",
  "엘리아이정":"Scopolamine",
  "오네론액":"Scopolamine",
  "이지트립시럽":"Scopolamine",
  "자메인정":"Scopolamine",
  "카이로정":"Scopolamine",
  "키드고액":"Scopolamine",
  "키미테정":"Scopolamine",
  "키미테패취":"Scopolamine",
  "타고가고액":"Scopolamine",
  "토스롱액":"Scopolamine",
  "토스롱에스액":"Scopolamine",
  "트라밍엔정":"Scopolamine",
  "파이런스캡슐":"Scopolamine",
  "파인탈에프츄어블정":"Scopolamine",
  "포나민정":"Scopolamine",
  "프리판주":"Scopolamine",
  "히스판주":"Scopolamine",
  "넥스페나신정":"Solifenacin",
  "뉴페신정":"Solifenacin",
  "라이트솔리페나신정":"Solifenacin",
  "메가솔페나정":"Solifenacin",
  "메디페나신정":"Solifenacin",
  "베나신정":"Solifenacin",
  "베솜니서방정":"Solifenacin",
  "베스칸정":"Solifenacin",
  "베시가드정":"Solifenacin",
  "베시금정":"Solifenacin",
  "베시나정":"Solifenacin",
  "베시드정":"Solifenacin",
  "베시민정":"Solifenacin",
  "베시솔정":"Solifenacin",
  "베시스타정":"Solifenacin",
  "베시시정":"Solifenacin",
  "베시칼린정":"Solifenacin",
  "베시캄정":"Solifenacin",
  "베시커버정":"Solifenacin",
  "베시케어정":"Solifenacin",
  "베시콜정":"Solifenacin",
  "베시퀸정":"Solifenacin",
  "베시큐정":"Solifenacin",
  "베시페나정":"Solifenacin",
  "보령솔리페나신정":"Solifenacin",
  "삼성솔리페나신정":"Solifenacin",
  "셀페리나정":"Solifenacin",
  "소울큐정":"Solifenacin",
  "솔나신정":"Solifenacin",
  "솔라신정":"Solifenacin",
  "솔라페신정":"Solifenacin",
  "솔레나신정":"Solifenacin",
  "솔리나신정":"Solifenacin",
  "솔리베정":"Solifenacin",
  "솔리스탑정":"Solifenacin",
  "솔리시톨정":"Solifenacin",
  "솔리신정":"Solifenacin",
  "솔리카정":"Solifenacin",
  "솔리케어정":"Solifenacin",
  "솔리콘정":"Solifenacin",
  "솔리테어정":"Solifenacin",
  "솔리토스구강붕해정":"Solifenacin",
  "솔리페나정":"Solifenacin",
  "솔리페노실정":"Solifenacin",
  "솔리페니정":"Solifenacin",
  "솔리페신정":"Solifenacin",
  "솔리페어정":"Solifenacin",
  "솔리프로정":"Solifenacin",
  "솔리프정":"Solifenacin",
  "솔베나정":"Solifenacin",
  "솔베신정":"Solifenacin",
  "솔신정":"Solifenacin",
  "솔토니신정":"Solifenacin",
  "솔페나신정":"Solifenacin",
  "솔페나정":"Solifenacin",
  "솔페락정":"Solifenacin",
  "솔페리신정":"Solifenacin",
  "솔페신정":"Solifenacin",
  "솔피펜정":"Solifenacin",
  "시스케어정":"Solifenacin",
  "씨엠케어정":"Solifenacin",
  "씨트케어정":"Solifenacin",
  "에어케어정":"Solifenacin",
  "에이케어에스정":"Solifenacin",
  "에이케어정":"Solifenacin",
  "엔티페나신정":"Solifenacin",
  "오비케어구강붕해필름":"Solifenacin",
  "오아비정":"Solifenacin",
  "오에이비정":"Solifenacin",
  "올페나신정":"Solifenacin",
  "요시케어정":"Solifenacin",
  "웰유로정":"Solifenacin",
  "유나케어정":"Solifenacin",
  "유로케어정":"Solifenacin",
  "유로테라정":"Solifenacin",
  "유로페나신정":"Solifenacin",
  "유리페나정":"Solifenacin",
  "유토케어정":"Solifenacin",
  "인페나신정":"Solifenacin",
  "케어실정":"Solifenacin",
  "큐어나신정":"Solifenacin",
  "현대솔리페나신숙신산염정":"Solifenacin",
  "휴페나신정":"Solifenacin",
  "네오시톨에스알정":"Tolterodine",
  "디루톨에스알정":"Tolterodine",
  "디트로딘에스알캡슐":"Tolterodine",
  "디트루시톨SR캡슐":"Tolterodine",
  "로시로딘서방정":"Tolterodine",
  "바이넥스톨터로딘서방정":"Tolterodine",
  "세다톨에스알정":"Tolterodine",
  "유레톨에스알정":"Tolterodine",
  "유로딘서방정":"Tolterodine",
  "유로카린서방정":"Tolterodine",
  "유로카린정":"Tolterodine",
  "유로큐서방정":"Tolterodine",
  "유로트롤정":"Tolterodine",
  "텔로딘정":"Tolterodine",
  "톨로스타정":"Tolterodine",
  "톨테로스SR정":"Tolterodine",
  "트리헥신정":"Trihexyphenidyl",
  "스파스몰리트당의정":"Trospium",

  // 2점 약물 상품명
  
};

// ── 대체 약물 매핑 ────────────────────────────────────────────
const ALTERNATIVE_MAP = {
  "Amitriptyline":      ["Paroxetine","Bupropion","Citalopram","Escitalopram","Fluoxetine","Mirtazapine","Trazodone","Venlafaxine","Sertraline"],
  "Atropine":           [],
  "Benztropine":        ["Amantadine","Bromocriptine","Entacapone","Pramipexole","Ropinirole","Selegiline"],
  "Brompheniramine":    ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Carbinoxamine":      ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Chlorpheniramine":   ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Chlorpromazine":     ["Amisulpride","Aripiprazole","Haloperidol","Paliperidone","Risperidone"],
  "Clemastine":         ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Clomipramine":       ["Paroxetine","Bupropion","Citalopram","Escitalopram","Fluoxetine","Mirtazapine","Venlafaxine"],
  "Clozapine":          [],
  "Dexbrompheniramine": ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Dexchlorpheniramine":["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Dicyclomine":        ["Alverine","Fenoverine","Papaverine","Tiropramide"],
  "Dimenhydrinate":     ["Cetirizine","Loratadine","Difenidol","Betahistine"],
  "Diphenhydramine":    ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Doxepin":            ["Paroxetine","Bupropion","Citalopram","Escitalopram","Fluoxetine","Mirtazapine","Trazodone","Venlafaxine"],
  "Doxylamine":         ["Cetirizine","Desloratadine","Levocetirizine","Loratadine"],
  "Fesoterodine":       [],
  "Flavoxate":          [],
  "Hydroxyzine":        ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Imidafenacin":       [],
  "Imipramine":         ["Paroxetine","Bupropion","Citalopram","Escitalopram","Fluoxetine","Mirtazapine","Venlafaxine"],
  "Meclizine":          ["Difenidol","Betahistine"],
  "Mequitazine":        ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Nortriptyline":      ["Bupropion","Citalopram","Escitalopram","Mirtazapine","Trazodone","Sertraline"],
  "Olanzapine":         ["Amisulpride","Aripiprazole","Haloperidol","Paliperidone","Risperidone","Ziprasidone"],
  "Orphenadrine":       ["Cyclobenzaprine","Tizanidine","Baclofen","Methocarbamol","Eperisone","Tolperisone"],
  "Oxybutynin":         [],
  "Pheniramine":        ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Pridinol":           ["Cyclobenzaprine","Tizanidine","Baclofen","Methocarbamol"],
  "Procyclidine":       ["Amantadine","Entacapone","Pramipexole","Ropinirole","Selegiline"],
  "Propiverine":        [],
  "Pyrilamine":         ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Scopolamine":        [],
  "Scopolamine Butylbromide": ["Alverine","Fenoverine","Papaverine","Tiropramide"],
  "Solifenacin":        [],
  "Tolterodine":        [],
  "Trihexyphenidyl":    ["Amantadine","Entacapone","Pramipexole","Ropinirole","Selegiline"],
  "Trospium":           [],
  "Amantadine":         ["Bromocriptine","Entacapone","Pramipexole","Ropinirole","Selegiline"],
  "Cimetidine":         ["Esomeprazole","Famotidine","Lansoprazole","Omeprazole","Pantoprazole"],
  "Clidinium":          ["Alverine","Fenoverine","Papaverine","Tiropramide"],
  "Cloperastine":       ["Dextromethorphan","Benzonatate"],
  "Cyclobenzaprine":    ["Baclofen","Methocarbamol","Eperisone","Tolperisone"],
  "Cyproheptadine":     ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Difenidol":          ["Cinnarizine","Betahistine"],
  "Glycopyrrolate":     ["Alverine","Fenoverine","Papaverine","Tiropramide"],
  "Levomepromazine":    ["Amisulpride","Aripiprazole","Haloperidol","Paliperidone","Risperidone"],
  "Loxapine":           ["Amisulpride","Aripiprazole","Haloperidol","Paliperidone","Risperidone"],
  "Molindone":          ["Amisulpride","Aripiprazole","Haloperidol","Paliperidone","Risperidone"],
  "Nefopam":            ["Acetaminophen","Celecoxib","Diclofenac","Ibuprofen","Meloxicam","Naproxen"],
  "Oxcarbazepine":      ["Carbamazepine","Gabapentin","Lamotrigine","Levetiracetam","Valproic acid"],
  "Paroxetine":         ["Duloxetine","Sertraline","Tianeptine"],
  "Perphenazine":       ["Amisulpride","Aripiprazole","Haloperidol","Paliperidone","Risperidone"],
  "Pethidine":          ["Acetaminophen","Celecoxib","Diclofenac","Ibuprofen","Meloxicam"],
  "Pimozide":           ["Amisulpride","Aripiprazole","Haloperidol","Paliperidone","Risperidone"],
  "Quetiapine":         ["Amisulpride","Aripiprazole","Haloperidol","Paliperidone","Risperidone"],
  "Tizanidine":         ["Baclofen","Methocarbamol","Eperisone","Tolperisone"],
  "Tramadol":           ["Acetaminophen","Celecoxib","Diclofenac","Ibuprofen","Meloxicam","Naproxen"],
  "Triprolidine":       ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Zotepine":           ["Amisulpride","Aripiprazole","Haloperidol","Paliperidone","Risperidone"],
  "Carbamazepine":      ["Levetiracetam","Lamotrigine"],
  "Cetirizine":         ["Fexofenadine","Azelastine","Bepotastine","Olopatadine"],
  "Cinnarizine":        ["Betahistine"],
  "Citalopram":         ["Duloxetine","Sertraline","Tianeptine"],
  "Clonazepam":         ["Levetiracetam"],
  "Codeine":            ["Acetaminophen","Celecoxib","Diclofenac","Ibuprofen","Naproxen"],
  "Desloratadine":      ["Fexofenadine","Azelastine","Bepotastine","Olopatadine"],
  "Dextromethorphan":   ["Benzonatate"],
  "Digoxin":            ["Dobutamine","Dopamine"],
  "Escitalopram":       ["Duloxetine","Sertraline","Tianeptine"],
  "Fentanyl":           ["Acetaminophen","Celecoxib","Diclofenac","Ibuprofen","Meloxicam"],
  "Fluoxetine":         ["Duloxetine","Sertraline","Tianeptine"],
  "Furosemide":         ["Hydrochlorothiazide","Indapamide","Spironolactone","Torsemide"],
  "Haloperidol":        ["Lithium","Nemonapride"],
  "Hydralazine":        ["Amlodipine","Atenolol","Bisoprolol","Enalapril","Losartan","Valsartan"],
  "Ketotifen":          ["Fexofenadine","Azelastine","Bepotastine","Olopatadine"],
  "Levocetirizine":     ["Fexofenadine","Azelastine","Bepotastine","Olopatadine"],
  "Loratadine":         ["Fexofenadine","Azelastine","Bepotastine","Olopatadine"],
  "Methocarbamol":      ["Eperisone","Tolperisone"],
  "Mirtazapine":        ["Duloxetine","Sertraline","Tianeptine"],
  "Morphine":           ["Acetaminophen","Celecoxib","Diclofenac","Ibuprofen","Meloxicam"],
  "Oxycodone":          ["Acetaminophen","Celecoxib","Diclofenac","Ibuprofen","Meloxicam"],
  "Ranitidine":         ["Esomeprazole","Famotidine","Lansoprazole","Omeprazole","Pantoprazole"],
  "Theophylline":       ["Salbutamol"],
  "Trazodone":          ["Duloxetine","Sertraline","Tianeptine"],
  "Trimebutine":        ["Domperidone","Metoclopramide"],
  "Venlafaxine":        ["Duloxetine","Sertraline","Tianeptine"],
};
