// ── ACB 약물 데이터베이스 ──────────────────────────────────────
// 참고: Boustani et al. (2008), Salahudeen et al. (2015), Kiesel et al. (2018)

const INGREDIENT_DB = [
  // ACB 3점 (Strong)
  {en:"Amitriptyline",      kr:"아미트리프틸린",        score:3, level:"Strong",   classKR:"삼환계 항우울제"},
  {en:"Atropine",           kr:"아트로핀",              score:3, level:"Strong",   classKR:"진경제/항무스카린제"},
  {en:"Benztropine",        kr:"벤즈트로핀",            score:3, level:"Strong",   classKR:"항파킨슨제"},
  {en:"Brompheniramine",    kr:"브롬페니라민",           score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Carbinoxamine",      kr:"카르비녹사민",           score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Chlorpheniramine",   kr:"클로르페니라민",         score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Chlorpromazine",     kr:"클로르프로마진",         score:3, level:"Strong",   classKR:"항정신병약"},
  {en:"Clemastine",         kr:"클레마스틴",             score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Clomipramine",       kr:"클로미프라민",           score:3, level:"Strong",   classKR:"삼환계 항우울제"},
  {en:"Clozapine",          kr:"클로자핀",               score:3, level:"Strong",   classKR:"비정형 항정신병제"},
  {en:"Dexbrompheniramine", kr:"덱스브롬페니라민",       score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Dexchlorpheniramine",kr:"덱스클로르페니라민",     score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Dicyclomine",        kr:"디사이클로민",           score:3, level:"Strong",   classKR:"위장관 진경제"},
  {en:"Dimenhydrinate",     kr:"디멘히드리나이트",       score:3, level:"Strong",   classKR:"항구토제/항히스타민제"},
  {en:"Diphenhydramine",    kr:"디펜히드라민",           score:3, level:"Strong",   classKR:"항히스타민제/수면유도"},
  {en:"Doxepin",            kr:"독세핀",                 score:3, level:"Strong",   classKR:"삼환계 항우울제"},
  {en:"Doxylamine",         kr:"독실아민",               score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Fesoterodine",       kr:"페소테로딘",             score:3, level:"Strong",   classKR:"과민성 방광 치료제"},
  {en:"Flavoxate",          kr:"플라복세이트",           score:3, level:"Strong",   classKR:"비뇨기계 진경제"},
  {en:"Hydroxyzine",        kr:"히드록시진",             score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Imidafenacin",       kr:"이미다페나신",           score:3, level:"Strong",   classKR:"비뇨기계 진경제"},
  {en:"Imipramine",         kr:"이미프라민",             score:3, level:"Strong",   classKR:"삼환계 항우울제"},
  {en:"Meclizine",          kr:"메클리진",               score:3, level:"Strong",   classKR:"항구토제/항현훈제"},
  {en:"Mequitazine",        kr:"메퀴타진",               score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Nortriptyline",      kr:"노르트립틸린",           score:3, level:"Strong",   classKR:"항우울제"},
  {en:"Olanzapine",         kr:"올란자핀",               score:3, level:"Strong",   classKR:"항정신병약"},
  {en:"Orphenadrine",       kr:"오르페나드린",           score:3, level:"Strong",   classKR:"근이완제"},
  {en:"Oxybutynin",         kr:"옥시부티닌",             score:3, level:"Strong",   classKR:"비뇨기계 진경제"},
  {en:"Pheniramine",        kr:"페니라민",               score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Pridinol",           kr:"프리디놀",               score:3, level:"Strong",   classKR:"근이완제"},
  {en:"Procyclidine",       kr:"프로사이클리딘",         score:3, level:"Strong",   classKR:"항파킨슨제"},
  {en:"Propiverine",        kr:"프로피베린",             score:3, level:"Strong",   classKR:"비뇨기계 진경제"},
  {en:"Pyrilamine",         kr:"피릴라민",               score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Scopolamine",        kr:"스코폴라민",             score:3, level:"Strong",   classKR:"항콜린제"},
  {en:"Scopolamine Butylbromide", kr:"스코폴라민 부틸브롬화물", score:3, level:"Strong", classKR:"위장관 진경제"},
  {en:"Solifenacin",        kr:"솔리페나신",             score:3, level:"Strong",   classKR:"비뇨기계 진경제"},
  {en:"Tolterodine",        kr:"톨테로딘",               score:3, level:"Strong",   classKR:"비뇨기계 진경제"},
  {en:"Trihexyphenidyl",    kr:"트리헥시페니딜",         score:3, level:"Strong",   classKR:"항파킨슨제"},
  {en:"Trospium",           kr:"트로스피움",             score:3, level:"Strong",   classKR:"비뇨기계 진경제"},

  // ACB 2점 (Moderate)
  {en:"Amantadine",         kr:"아만타딘",               score:2, level:"Moderate", classKR:"항파킨슨제"},
  {en:"Cimetidine",         kr:"시메티딘",               score:2, level:"Moderate", classKR:"H2 차단제"},
  {en:"Clidinium",          kr:"클리디늄",               score:2, level:"Moderate", classKR:"위장관 항콜린제"},
  {en:"Cloperastine",       kr:"클로페라스틴",           score:2, level:"Moderate", classKR:"진해제"},
  {en:"Cyclobenzaprine",    kr:"사이클로벤자프린",       score:2, level:"Moderate", classKR:"근이완제"},
  {en:"Cyproheptadine",     kr:"사이프로헵타딘",         score:2, level:"Moderate", classKR:"항히스타민제"},
  {en:"Difenidol",          kr:"디페니돌",               score:2, level:"Moderate", classKR:"항현훈제"},
  {en:"Glycopyrrolate",     kr:"글리코피롤레이트",       score:2, level:"Moderate", classKR:"위장관 항콜린제"},
  {en:"Levomepromazine",    kr:"레보메프로마진",         score:2, level:"Moderate", classKR:"항정신병약"},
  {en:"Loxapine",           kr:"록사핀",                 score:2, level:"Moderate", classKR:"항정신병약"},
  {en:"Molindone",          kr:"몰린돈",                 score:2, level:"Moderate", classKR:"항정신병약"},
  {en:"Nefopam",            kr:"네포팜",                 score:2, level:"Moderate", classKR:"진통제"},
  {en:"Oxcarbazepine",      kr:"옥스카르바제핀",         score:2, level:"Moderate", classKR:"항전간제"},
  {en:"Paroxetine",         kr:"파록세틴",               score:2, level:"Moderate", classKR:"항우울제 (SSRI)"},
  {en:"Perphenazine",       kr:"퍼페나진",               score:2, level:"Moderate", classKR:"항정신병약"},
  {en:"Pethidine",          kr:"페티딘",                 score:2, level:"Moderate", classKR:"진통제"},
  {en:"Pimozide",           kr:"피모자이드",             score:2, level:"Moderate", classKR:"항정신병약"},
  {en:"Quetiapine",         kr:"쿠에티아핀",             score:2, level:"Moderate", classKR:"항정신병약"},
  {en:"Tizanidine",         kr:"티자니딘",               score:2, level:"Moderate", classKR:"근이완제"},
  {en:"Tramadol",           kr:"트라마돌",               score:2, level:"Moderate", classKR:"진통제"},
  {en:"Triprolidine",       kr:"트리프로리딘",           score:2, level:"Moderate", classKR:"항히스타민제"},
  {en:"Zotepine",           kr:"조테핀",                 score:2, level:"Moderate", classKR:"항정신병약"},

  // ACB 1점 (Weak)
  {en:"Alprazolam",         kr:"알프라졸람",             score:1, level:"Weak",     classKR:"항불안제"},
  {en:"Amisulpride",        kr:"아미설프리드",           score:1, level:"Weak",     classKR:"항정신병약"},
  {en:"Aripiprazole",       kr:"아리피프라졸",           score:1, level:"Weak",     classKR:"항정신병약"},
  {en:"Baclofen",           kr:"바클로펜",               score:1, level:"Weak",     classKR:"근이완제"},
  {en:"Blonanserin",        kr:"블로난세린",             score:1, level:"Weak",     classKR:"항정신병약"},
  {en:"Bupropion",          kr:"부프로피온",             score:1, level:"Weak",     classKR:"항우울제"},
  {en:"Carbamazepine",      kr:"카르바마제핀",           score:1, level:"Weak",     classKR:"항경련제"},
  {en:"Cetirizine",         kr:"세티리진",               score:1, level:"Weak",     classKR:"항히스타민제"},
  {en:"Chlordiazepoxide",   kr:"클로르디아제폭사이드",   score:1, level:"Weak",     classKR:"항불안제"},
  {en:"Cinnarizine",        kr:"신나리진",               score:1, level:"Weak",     classKR:"항현훈제"},
  {en:"Citalopram",         kr:"시탈로프람",             score:1, level:"Weak",     classKR:"항우울제"},
  {en:"Clonazepam",         kr:"클로나제팜",             score:1, level:"Weak",     classKR:"항경련제/항불안제"},
  {en:"Codeine",            kr:"코데인",                 score:1, level:"Weak",     classKR:"진통제"},
  {en:"Desloratadine",      kr:"데슬로라타딘",           score:1, level:"Weak",     classKR:"항히스타민제"},
  {en:"Desvenlafaxine",     kr:"데스벤라팍신",           score:1, level:"Weak",     classKR:"항우울제 (SNRI)"},
  {en:"Dextromethorphan",   kr:"덱스트로메토르판",       score:1, level:"Weak",     classKR:"진해제"},
  {en:"Diazepam",           kr:"디아제팜",               score:1, level:"Weak",     classKR:"항불안제"},
  {en:"Digoxin",            kr:"디곡신",                 score:1, level:"Weak",     classKR:"강심제"},
  {en:"Emedastine",         kr:"에메다스틴",             score:1, level:"Weak",     classKR:"항히스타민제"},
  {en:"Escitalopram",       kr:"에스시탈로프람",         score:1, level:"Weak",     classKR:"항우울제"},
  {en:"Fentanyl",           kr:"펜타닐",                 score:1, level:"Weak",     classKR:"진통제"},
  {en:"Fluoxetine",         kr:"플루옥세틴",             score:1, level:"Weak",     classKR:"항우울제 (SSRI)"},
  {en:"Furosemide",         kr:"푸로세미드",             score:1, level:"Weak",     classKR:"이뇨제"},
  {en:"Haloperidol",        kr:"할로페리돌",             score:1, level:"Weak",     classKR:"항정신병약"},
  {en:"Hydralazine",        kr:"하이드랄라진",           score:1, level:"Weak",     classKR:"혈압강하제"},
  {en:"Hydrocortisone",     kr:"하이드로코르티손",       score:1, level:"Weak",     classKR:"스테로이드"},
  {en:"Ketotifen",          kr:"케토티펜",               score:1, level:"Weak",     classKR:"항히스타민제"},
  {en:"Levocetirizine",     kr:"레보세티리진",           score:1, level:"Weak",     classKR:"항히스타민제"},
  {en:"Loperamide",         kr:"로페라마이드",           score:1, level:"Weak",     classKR:"지사제"},
  {en:"Loratadine",         kr:"로라타딘",               score:1, level:"Weak",     classKR:"항히스타민제"},
  {en:"Lorazepam",          kr:"로라제팜",               score:1, level:"Weak",     classKR:"항불안제"},
  {en:"Methocarbamol",      kr:"메토카르바몰",           score:1, level:"Weak",     classKR:"근이완제"},
  {en:"Midazolam",          kr:"미다졸람",               score:1, level:"Weak",     classKR:"진정제"},
  {en:"Mirtazapine",        kr:"미르타자핀",             score:1, level:"Weak",     classKR:"항우울제"},
  {en:"Morphine",           kr:"모르핀",                 score:1, level:"Weak",     classKR:"진통제"},
  {en:"Oxycodone",          kr:"옥시코돈",               score:1, level:"Weak",     classKR:"진통제"},
  {en:"Paliperidone",       kr:"팔리페리돈",             score:1, level:"Weak",     classKR:"항정신병약"},
  {en:"Prednisolone",       kr:"프레드니솔론",           score:1, level:"Weak",     classKR:"스테로이드"},
  {en:"Ranitidine",         kr:"라니티딘",               score:1, level:"Weak",     classKR:"위산분비억제"},
  {en:"Risperidone",        kr:"리스페리돈",             score:1, level:"Weak",     classKR:"항정신병약"},
  {en:"Theophylline",       kr:"테오필린",               score:1, level:"Weak",     classKR:"기관지확장제"},
  {en:"Trazodone",          kr:"트라조돈",               score:1, level:"Weak",     classKR:"항우울제/수면제"},
  {en:"Triazolam",          kr:"트리아졸람",             score:1, level:"Weak",     classKR:"수면제"},
  {en:"Trimebutine",        kr:"트리메부틴",             score:1, level:"Weak",     classKR:"위장관운동조절제"},
  {en:"Venlafaxine",        kr:"벤라팍신",               score:1, level:"Weak",     classKR:"항우울제 (SNRI)"},
  {en:"Ziprasidone",        kr:"지프라시돈",             score:1, level:"Weak",     classKR:"항정신병약"},
];

// ── 상품명 → 성분명 매핑 ─────────────────────────────────────
const BRAND_MAP = {
  "에트라빌정":"Amitriptyline","에나폰정":"Amitriptyline","토프라닐정":"Imipramine",
  "아나프라닐정":"Clomipramine","아벤틸정":"Nortriptyline","시네콴정":"Doxepin",
  "프로작캡슐":"Fluoxetine","팍실정":"Paroxetine","렉사프로정":"Escitalopram",
  "시프람정":"Citalopram","미르타불정":"Mirtazapine","레메론정":"Mirtazapine",
  "웰부트린정":"Bupropion","이펙사서방정":"Venlafaxine",
  "자이프렉사정":"Olanzapine","쿠에타핀정":"Quetiapine","리스페달정":"Risperidone",
  "에이리파이정":"Aripiprazole","클로자릴정":"Clozapine","할돌정":"Haloperidol",
  "콘타민정":"Chlorpromazine",
  "지르텍정":"Cetirizine","클라리틴정":"Loratadine","아에리우스정":"Desloratadine",
  "씨잘정":"Levocetirizine","아타락스정":"Hydroxyzine","유니히스정":"Hydroxyzine",
  "판콜에이내복액":"Chlorpheniramine","화이투벤시럽":"Chlorpheniramine",
  "래피콜데이연질캡슐":"Brompheniramine","유니좀정":"Doxylamine",
  "자낙스정":"Alprazolam","할시온정":"Triazolam","리보트릴정":"Clonazepam",
  "클로나제팜정":"Clonazepam","로라제팜정":"Lorazepam","디아제팜정":"Diazepam",
  "트리돌정":"Tramadol","울트라셋정":"Tramadol","우도락캡슐":"Tramadol",
  "리오레살정":"Baclofen","자나플렉스정":"Tizanidine","플렉세릴정":"Cyclobenzaprine",
  "노르플렉스정":"Orphenadrine","메토카르바몰정":"Methocarbamol",
  "아르탄정":"Trihexyphenidyl","트리오신정":"Trihexyphenidyl",
  "명인벤즈트로핀정":"Benztropine","환인벤즈트로핀정":"Benztropine",
  "파킨캡슐":"Amantadine","아만타딘캡슐":"Amantadine",
  "부스코판정":"Scopolamine Butylbromide","스코부틸정":"Scopolamine Butylbromide",
  "스코폴라민패취":"Scopolamine","키미테패취":"Scopolamine",
  "베시케어정":"Solifenacin","디트로판정":"Oxybutynin",
  "드리틸정":"Trospium","디트루시톨정":"Tolterodine",
  "잔탁정":"Ranitidine","타가메트정":"Cimetidine",
  "트리렙탈정":"Oxcarbazepine","테그레톨정":"Carbamazepine",
  "케토티펜정":"Ketotifen",
};

// ── 대체 약물 매핑 ────────────────────────────────────────────
const ALTERNATIVE_MAP = {
  "Amitriptyline":      ["Paroxetine","Bupropion","Citalopram","Escitalopram","Fluoxetine","Mirtazapine","Trazodone","Venlafaxine","Sertraline"],
  "Atropine":           [],
  "Benztropine":        ["Amantadine","Bromocriptine","Entacapone","Pramipexole","Ropinirole","Selegiline"],
  "Brompheniramine":    ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Carbinoxamine":      ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Chlorpheniramine":   ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Chlorpromazine":     ["Amisulpride","Aripiprazole","Haloperidol","Paliperidone","Risperidone"],
  "Clemastine":         ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Clomipramine":       ["Paroxetine","Bupropion","Citalopram","Escitalopram","Fluoxetine","Mirtazapine","Venlafaxine"],
  "Clozapine":          [],
  "Dexbrompheniramine": ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Dexchlorpheniramine":["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Dicyclomine":        ["Alverine","Fenoverine","Papaverine","Tiropramide"],
  "Dimenhydrinate":     ["Cetirizine","Loratadine","Difenidol","Betahistine"],
  "Diphenhydramine":    ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Doxepin":            ["Paroxetine","Bupropion","Citalopram","Escitalopram","Fluoxetine","Mirtazapine","Trazodone","Venlafaxine"],
  "Doxylamine":         ["Cetirizine","Desloratadine","Levocetirizine","Loratadine"],
  "Fesoterodine":       [],
  "Flavoxate":          [],
  "Hydroxyzine":        ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Imidafenacin":       [],
  "Imipramine":         ["Paroxetine","Bupropion","Citalopram","Escitalopram","Fluoxetine","Mirtazapine","Venlafaxine"],
  "Meclizine":          ["Difenidol","Betahistine"],
  "Mequitazine":        ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Nortriptyline":      ["Bupropion","Citalopram","Escitalopram","Mirtazapine","Trazodone","Sertraline"],
  "Olanzapine":         ["Amisulpride","Aripiprazole","Haloperidol","Paliperidone","Risperidone","Ziprasidone"],
  "Orphenadrine":       ["Cyclobenzaprine","Tizanidine","Baclofen","Methocarbamol","Eperisone","Tolperisone"],
  "Oxybutynin":         [],
  "Pheniramine":        ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Pridinol":           ["Cyclobenzaprine","Tizanidine","Baclofen","Methocarbamol"],
  "Procyclidine":       ["Amantadine","Entacapone","Pramipexole","Ropinirole","Selegiline"],
  "Propiverine":        [],
  "Pyrilamine":         ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Scopolamine":        [],
  "Scopolamine Butylbromide": ["Alverine","Fenoverine","Papaverine","Tiropramide"],
  "Solifenacin":        [],
  "Tolterodine":        [],
  "Trihexyphenidyl":    ["Amantadine","Entacapone","Pramipexole","Ropinirole","Selegiline"],
  "Trospium":           [],
  "Amantadine":         ["Bromocriptine","Entacapone","Pramipexole","Ropinirole","Selegiline"],
  "Cimetidine":         ["Esomeprazole","Famotidine","Lansoprazole","Omeprazole","Pantoprazole"],
  "Clidinium":          ["Alverine","Fenoverine","Papaverine","Tiropramide"],
  "Cloperastine":       ["Dextromethorphan","Benzonatate"],
  "Cyclobenzaprine":    ["Baclofen","Methocarbamol","Eperisone","Tolperisone"],
  "Cyproheptadine":     ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Difenidol":          ["Cinnarizine","Betahistine"],
  "Glycopyrrolate":     ["Alverine","Fenoverine","Papaverine","Tiropramide"],
  "Levomepromazine":    ["Amisulpride","Aripiprazole","Haloperidol","Paliperidone","Risperidone"],
  "Loxapine":           ["Amisulpride","Aripiprazole","Haloperidol","Paliperidone","Risperidone"],
  "Molindone":          ["Amisulpride","Aripiprazole","Haloperidol","Paliperidone","Risperidone"],
  "Nefopam":            ["Acetaminophen","Celecoxib","Diclofenac","Ibuprofen","Meloxicam","Naproxen"],
  "Oxcarbazepine":      ["Carbamazepine","Gabapentin","Lamotrigine","Levetiracetam","Valproic acid"],
  "Paroxetine":         ["Duloxetine","Sertraline","Tianeptine"],
  "Perphenazine":       ["Amisulpride","Aripiprazole","Haloperidol","Paliperidone","Risperidone"],
  "Pethidine":          ["Acetaminophen","Celecoxib","Diclofenac","Ibuprofen","Meloxicam"],
  "Pimozide":           ["Amisulpride","Aripiprazole","Haloperidol","Paliperidone","Risperidone"],
  "Quetiapine":         ["Amisulpride","Aripiprazole","Haloperidol","Paliperidone","Risperidone"],
  "Tizanidine":         ["Baclofen","Methocarbamol","Eperisone","Tolperisone"],
  "Tramadol":           ["Acetaminophen","Celecoxib","Diclofenac","Ibuprofen","Meloxicam","Naproxen"],
  "Triprolidine":       ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Zotepine":           ["Amisulpride","Aripiprazole","Haloperidol","Paliperidone","Risperidone"],
  "Carbamazepine":      ["Levetiracetam","Lamotrigine"],
  "Cetirizine":         ["Fexofenadine","Azelastine","Bepotastine","Olopatadine"],
  "Cinnarizine":        ["Betahistine"],
  "Citalopram":         ["Duloxetine","Sertraline","Tianeptine"],
  "Clonazepam":         ["Levetiracetam"],
  "Codeine":            ["Acetaminophen","Celecoxib","Diclofenac","Ibuprofen","Naproxen"],
  "Desloratadine":      ["Fexofenadine","Azelastine","Bepotastine","Olopatadine"],
  "Dextromethorphan":   ["Benzonatate"],
  "Digoxin":            ["Dobutamine","Dopamine"],
  "Escitalopram":       ["Duloxetine","Sertraline","Tianeptine"],
  "Fentanyl":           ["Acetaminophen","Celecoxib","Diclofenac","Ibuprofen","Meloxicam"],
  "Fluoxetine":         ["Duloxetine","Sertraline","Tianeptine"],
  "Furosemide":         ["Hydrochlorothiazide","Indapamide","Spironolactone","Torsemide"],
  "Haloperidol":        ["Lithium","Nemonapride"],
  "Hydralazine":        ["Amlodipine","Atenolol","Bisoprolol","Enalapril","Losartan","Valsartan"],
  "Ketotifen":          ["Fexofenadine","Azelastine","Bepotastine","Olopatadine"],
  "Levocetirizine":     ["Fexofenadine","Azelastine","Bepotastine","Olopatadine"],
  "Loratadine":         ["Fexofenadine","Azelastine","Bepotastine","Olopatadine"],
  "Methocarbamol":      ["Eperisone","Tolperisone"],
  "Mirtazapine":        ["Duloxetine","Sertraline","Tianeptine"],
  "Morphine":           ["Acetaminophen","Celecoxib","Diclofenac","Ibuprofen","Meloxicam"],
  "Oxycodone":          ["Acetaminophen","Celecoxib","Diclofenac","Ibuprofen","Meloxicam"],
  "Ranitidine":         ["Esomeprazole","Famotidine","Lansoprazole","Omeprazole","Pantoprazole"],
  "Theophylline":       ["Salbutamol"],
  "Trazodone":          ["Duloxetine","Sertraline","Tianeptine"],
  "Trimebutine":        ["Domperidone","Metoclopramide"],
  "Venlafaxine":        ["Duloxetine","Sertraline","Tianeptine"],
};
