// ── ACB 약물 데이터베이스 ──────────────────────────────────────
// 참고: Boustani et al. (2008), Salahudeen et al. (2015), Kiesel et al. (2018)

const INGREDIENT_DB = [
  // ACB 0점 (Safe) — 엑셀 DB 기준 304종
{en:"Acarbose", kr:"아카보스", score:0, level:"Safe", classKR:"당뇨병 치료제"},
  {en:"Acetaminophen", kr:"아세트아미노펜", score:0, level:"Safe", classKR:"진통제"},
  {en:"Acetazolamide", kr:"아세타졸라미드", score:0, level:"Safe", classKR:"안과용제"},
  {en:"Acitretin", kr:"아시트레틴", score:0, level:"Safe", classKR:"피부과용제"},
  {en:"Acyclovir", kr:"아시클로버", score:0, level:"Safe", classKR:"항바이러스제"},
  {en:"Adenosine", kr:"아데노신", score:0, level:"Safe", classKR:"항부정맥제"},
  {en:"Alendronate", kr:"알렌드로네이트", score:0, level:"Safe", classKR:"골다공증 치료제"},
  {en:"Allopurinol", kr:"알로푸리놀", score:0, level:"Safe", classKR:"통풍 치료제"},
  {en:"Alverine", kr:"알베린", score:0, level:"Safe", classKR:"위장관 진경제"},
  {en:"Amiloride", kr:"아밀로라이드", score:0, level:"Safe", classKR:"이뇨제"},
  {en:"Amiodarone", kr:"아미오다론", score:0, level:"Safe", classKR:"항부정맥제"},
  {en:"Amlodipine", kr:"암로디핀", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Amoxicillin", kr:"아모시실린", score:0, level:"Safe", classKR:"항생제"},
  {en:"Ampicillin", kr:"암피실린", score:0, level:"Safe", classKR:"항생제"},
  {en:"Anagrelide", kr:"아나그렐리드", score:0, level:"Safe", classKR:"항종양제"},
  {en:"Anastrozole", kr:"아나스트로졸", score:0, level:"Safe", classKR:"항종양제"},
  {en:"Ascorbic acid", kr:"아스코르브산", score:0, level:"Safe", classKR:"비타민제"},
  {en:"Aspirin", kr:"아스피린", score:0, level:"Safe", classKR:"진통제"},
  {en:"Atenolol", kr:"아테놀롤", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Atorvastatin", kr:"아토르바스타틴", score:0, level:"Safe", classKR:"고지혈증 치료제"},
  {en:"Azathioprine", kr:"아자티오프린", score:0, level:"Safe", classKR:"면역억제제"},
  {en:"Azelastine", kr:"아젤라스틴", score:0, level:"Safe", classKR:"항히스타민제"},
  {en:"Azithromycin", kr:"아지트로마이신", score:0, level:"Safe", classKR:"항생제"},
  {en:"Benzonatate", kr:"벤조나테이트", score:0, level:"Safe", classKR:"진해제"},
  {en:"Bepotastine", kr:"베포타스틴", score:0, level:"Safe", classKR:"항히스타민제"},
  {en:"Beta-carotene", kr:"베타카로틴", score:0, level:"Safe", classKR:"비타민제"},
  {en:"Betahistine", kr:"베타히스틴", score:0, level:"Safe", classKR:"항현훈제"},
  {en:"Betaine", kr:"베타인", score:0, level:"Safe", classKR:"소화제"},
  {en:"Betaxolol", kr:"베탁솔롤", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Bethanechol", kr:"베타네콜", score:0, level:"Safe", classKR:"콜린제"},
  {en:"Bicalutamide", kr:"비칼루타미드", score:0, level:"Safe", classKR:"항종양제"},
  {en:"Bisacodyl", kr:"비사코딜", score:0, level:"Safe", classKR:"하제"},
  {en:"Bisoprolol", kr:"비소프롤롤", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Bromhexine", kr:"브롬헥신", score:0, level:"Safe", classKR:"거담제"},
  {en:"Bromocriptine", kr:"브로모크립틴", score:0, level:"Safe", classKR:"항파킨슨제"},
  {en:"Buprenorphine", kr:"부프레노르핀", score:0, level:"Safe", classKR:"진통제"},
  {en:"Cabergoline", kr:"카베골린", score:0, level:"Safe", classKR:"항파킨슨제"},
  {en:"Caffeine", kr:"카페인", score:0, level:"Safe", classKR:"중추신경자극제"},
  {en:"Calcitriol", kr:"칼시트리올", score:0, level:"Safe", classKR:"비타민제"},
  {en:"Candesartan", kr:"칸데사르탄", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Captopril", kr:"캡토프릴", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Carnitine", kr:"카르니틴", score:0, level:"Safe", classKR:"대사성 약물"},
  {en:"Carvedilol", kr:"카르베딜롤", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Casanthranol", kr:"카산트라놀", score:0, level:"Safe", classKR:"하제"},
  {en:"Cefaclor", kr:"세파클러", score:0, level:"Safe", classKR:"항생제"},
  {en:"Cefamandole", kr:"세파만돌", score:0, level:"Safe", classKR:"항생제"},
  {en:"Cefazolin", kr:"세파졸린", score:0, level:"Safe", classKR:"항생제"},
  {en:"Cefixime", kr:"세픽심", score:0, level:"Safe", classKR:"항생제"},
  {en:"Cefoxitin", kr:"세포시틴", score:0, level:"Safe", classKR:"항생제"},
  {en:"Ceftriaxone", kr:"세프트리아손", score:0, level:"Safe", classKR:"항생제"},
  {en:"Cefuroxime", kr:"세푸록심", score:0, level:"Safe", classKR:"항생제"},
  {en:"Celecoxib", kr:"세레콕시브", score:0, level:"Safe", classKR:"진통제"},
  {en:"Cephalexin", kr:"세팔렉신", score:0, level:"Safe", classKR:"항생제"},
  {en:"Cephalothin", kr:"세팔로틴", score:0, level:"Safe", classKR:"항생제"},
  {en:"Chlorambucil", kr:"클로람부실", score:0, level:"Safe", classKR:"항종양제"},
  {en:"Chlorthalidone", kr:"클로르탈리돈", score:0, level:"Safe", classKR:"이뇨제"},
  {en:"Chlorzoxazone", kr:"클로르족사존", score:0, level:"Safe", classKR:"근이완제"},
  {en:"Cholestyramine", kr:"콜레스티라민", score:0, level:"Safe", classKR:"고지혈증 치료제"},
  {en:"Chondroitin", kr:"콘드로이틴", score:0, level:"Safe", classKR:"연골보호제"},
  {en:"Cilostazol", kr:"실로스타졸", score:0, level:"Safe", classKR:"항혈소판제"},
  {en:"Ciprofloxacin", kr:"시프로플록사신", score:0, level:"Safe", classKR:"항생제"},
  {en:"Clarithromycin", kr:"클래리스로마이신", score:0, level:"Safe", classKR:"항생제"},
  {en:"Clindamycin", kr:"클린다마이신", score:0, level:"Safe", classKR:"항생제"},
  {en:"Clonidine", kr:"클로니딘", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Colchicine", kr:"콜히친", score:0, level:"Safe", classKR:"통풍 치료제"},
  {en:"Cyanocobalamin", kr:"시아노코발라민", score:0, level:"Safe", classKR:"비타민제"},
  {en:"Cyclophosphamide", kr:"사이클로포스파미드", score:0, level:"Safe", classKR:"항종양제"},
  {en:"Cycloserine", kr:"사이클로세린", score:0, level:"Safe", classKR:"항결핵제"},
  {en:"Cyclosporine", kr:"사이클로스포린", score:0, level:"Safe", classKR:"면역억제제"},
  {en:"Danazol", kr:"다나졸", score:0, level:"Safe", classKR:"성호르몬제"},
  {en:"Dantrolene", kr:"단트롤렌", score:0, level:"Safe", classKR:"근이완제"},
  {en:"Darbepoetin", kr:"다베포에틴", score:0, level:"Safe", classKR:"조혈제"},
  {en:"Deferasirox", kr:"데페라시록스", score:0, level:"Safe", classKR:"킬레이트제"},
  {en:"Dextran", kr:"덱스트란", score:0, level:"Safe", classKR:"혈장증량제"},
  {en:"Diclofenac", kr:"디클로페낙", score:0, level:"Safe", classKR:"진통제"},
  {en:"Diltiazem", kr:"딜티아젬", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Dirithromycin", kr:"디리트로마이신", score:0, level:"Safe", classKR:"항생제"},
  {en:"Dobutamine", kr:"도부타민", score:0, level:"Safe", classKR:"강심제"},
  {en:"Docusate", kr:"도큐세이트", score:0, level:"Safe", classKR:"하제"},
  {en:"Domperidone", kr:"돔페리돈", score:0, level:"Safe", classKR:"위장관운동조절제"},
  {en:"Donepezil", kr:"도네페질", score:0, level:"Safe", classKR:"항치매제"},
  {en:"Dopamine", kr:"도파민", score:0, level:"Safe", classKR:"강심제"},
  {en:"Doxazosin", kr:"독사조신", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Doxycycline", kr:"독시사이클린", score:0, level:"Safe", classKR:"항생제"},
  {en:"Duloxetine", kr:"둘록세틴", score:0, level:"Safe", classKR:"항우울제"},
  {en:"Dydrogesterone", kr:"디드로게스테론", score:0, level:"Safe", classKR:"성호르몬제"},
  {en:"Ebastine", kr:"에바스틴", score:0, level:"Safe", classKR:"항히스타민제"},
  {en:"Enalapril", kr:"에날라프릴", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Entacapone", kr:"엔타카폰", score:0, level:"Safe", classKR:"항파킨슨제"},
  {en:"Eperisone", kr:"에페리손", score:0, level:"Safe", classKR:"근이완제"},
  {en:"Epinastine", kr:"에피나스틴", score:0, level:"Safe", classKR:"항히스타민제"},
  {en:"Epinephrine", kr:"에피네프린", score:0, level:"Safe", classKR:"승압제"},
  {en:"Epoetin alfa", kr:"에포에틴 알파", score:0, level:"Safe", classKR:"조혈제"},
  {en:"Eprosartan", kr:"에프로사르탄", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Ergocalciferol", kr:"에르고칼시페롤", score:0, level:"Safe", classKR:"비타민제"},
  {en:"Ergoloid mesylates", kr:"에르고로이드메실산염", score:0, level:"Safe", classKR:"혈관확장제"},
  {en:"Erythromycin", kr:"에리트로마이신", score:0, level:"Safe", classKR:"항생제"},
  {en:"Esomeprazole", kr:"에스오메프라졸", score:0, level:"Safe", classKR:"위산분비억제"},
  {en:"Estrogen preparation", kr:"에스트로겐 제제", score:0, level:"Safe", classKR:"성호르몬제"},
  {en:"Ethambutol", kr:"에탐부톨", score:0, level:"Safe", classKR:"항결핵제"},
  {en:"Etidronate", kr:"에티드로네이트", score:0, level:"Safe", classKR:"골다공증 치료제"},
  {en:"Etodolac", kr:"에토돌락", score:0, level:"Safe", classKR:"진통제"},
  {en:"Ezetimibe", kr:"에제티미브", score:0, level:"Safe", classKR:"고지혈증 치료제"},
  {en:"Famciclovir", kr:"팜시클로버", score:0, level:"Safe", classKR:"항바이러스제"},
  {en:"Famotidine", kr:"파모티딘", score:0, level:"Safe", classKR:"위산분비억제"},
  {en:"Felodipine", kr:"펠로디핀", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Fenofibrate", kr:"페노피브레이트", score:0, level:"Safe", classKR:"고지혈증 치료제"},
  {en:"Fenoverine", kr:"페노베린", score:0, level:"Safe", classKR:"위장관 진경제"},
  {en:"Fexofenadine", kr:"펙소페나딘", score:0, level:"Safe", classKR:"항히스타민제"},
  {en:"Filgrastim", kr:"필그라스팀", score:0, level:"Safe", classKR:"조혈제"},
  {en:"Finasteride", kr:"피나스테리드", score:0, level:"Safe", classKR:"전립선비대증 치료제"},
  {en:"Fish oil", kr:"어유", score:0, level:"Safe", classKR:"지질조절제"},
  {en:"Flecainide", kr:"플레카이니드", score:0, level:"Safe", classKR:"항부정맥제"},
  {en:"Fluconazole", kr:"플루코나졸", score:0, level:"Safe", classKR:"항진균제"},
  {en:"Flumazenil", kr:"플루마제닐", score:0, level:"Safe", classKR:"해독제"},
  {en:"Fluorouracil", kr:"플루오로우라실", score:0, level:"Safe", classKR:"항종양제"},
  {en:"Flutamide", kr:"플루타미드", score:0, level:"Safe", classKR:"항종양제"},
  {en:"Fluvastatin", kr:"플루바스타틴", score:0, level:"Safe", classKR:"고지혈증 치료제"},
  {en:"Folic acid", kr:"엽산", score:0, level:"Safe", classKR:"비타민제"},
  {en:"Fosinopril", kr:"포시노프릴", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Frangula", kr:"프랑굴라", score:0, level:"Safe", classKR:"하제"},
  {en:"Gabapentin", kr:"가바펜틴", score:0, level:"Safe", classKR:"항전간제"},
  {en:"Galantamine", kr:"갈란타민", score:0, level:"Safe", classKR:"항치매제"},
  {en:"Gemfibrozil", kr:"겜피브로질", score:0, level:"Safe", classKR:"고지혈증 치료제"},
  {en:"Gentamicin", kr:"젠타마이신", score:0, level:"Safe", classKR:"항생제"},
  {en:"Ginkgo", kr:"은행엽엑스", score:0, level:"Safe", classKR:"항치매제"},
  {en:"Ginseng", kr:"인삼", score:0, level:"Safe", classKR:"생약제제"},
  {en:"Glibenclamide", kr:"글리벤클라미드", score:0, level:"Safe", classKR:"당뇨병 치료제"},
  {en:"Gliclazide", kr:"글리클라지드", score:0, level:"Safe", classKR:"당뇨병 치료제"},
  {en:"Glimepiride", kr:"글리메피리드", score:0, level:"Safe", classKR:"당뇨병 치료제"},
  {en:"Glipizide", kr:"글리피지드", score:0, level:"Safe", classKR:"당뇨병 치료제"},
  {en:"Glucosamine", kr:"글루코사민", score:0, level:"Safe", classKR:"연골보호제"},
  {en:"Glucose", kr:"포도당", score:0, level:"Safe", classKR:"영양제"},
  {en:"Goserelin acetate", kr:"고세렐린", score:0, level:"Safe", classKR:"항종양제"},
  {en:"Histidine", kr:"히스티딘", score:0, level:"Safe", classKR:"아미노산제"},
  {en:"Hydrochlorothiazide", kr:"히드로클로로티아지드", score:0, level:"Safe", classKR:"이뇨제"},
  {en:"Hydromorphone", kr:"하이드로모르폰", score:0, level:"Safe", classKR:"진통제"},
  {en:"Hydroxychloroquine", kr:"히드록시클로로퀸", score:0, level:"Safe", classKR:"항류마티스제"},
  {en:"Hydroxyurea", kr:"하이드록시우레아", score:0, level:"Safe", classKR:"항종양제"},
  {en:"Ibuprofen", kr:"이부프로펜", score:0, level:"Safe", classKR:"진통제"},
  {en:"Imipenem", kr:"이미페넴", score:0, level:"Safe", classKR:"항생제"},
  {en:"Indapamide", kr:"인다파미드", score:0, level:"Safe", classKR:"이뇨제"},
  {en:"Influenza virus vaccine", kr:"인플루엔자 백신", score:0, level:"Safe", classKR:"백신"},
  {en:"Insulin", kr:"인슐린", score:0, level:"Safe", classKR:"당뇨병 치료제"},
  {en:"Irbesartan", kr:"이르베사르탄", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Iron preparations", kr:"철분 제제", score:0, level:"Safe", classKR:"철분제제"},
  {en:"Isoniazid", kr:"이소니아지드", score:0, level:"Safe", classKR:"항결핵제"},
  {en:"Isosorbide", kr:"이소소르비드", score:0, level:"Safe", classKR:"항협심증제"},
  {en:"Ketoprofen", kr:"케토프로펜", score:0, level:"Safe", classKR:"진통제"},
  {en:"Ketorolac", kr:"케토롤락", score:0, level:"Safe", classKR:"진통제"},
  {en:"Labetalol", kr:"라베탈롤", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Lactic acid bacteria", kr:"유산균", score:0, level:"Safe", classKR:"정장제"},
  {en:"Lactulose", kr:"락툴로오스", score:0, level:"Safe", classKR:"하제"},
  {en:"Lamotrigine", kr:"라모트리진", score:0, level:"Safe", classKR:"항전간제"},
  {en:"Lansoprazole", kr:"란소프라졸", score:0, level:"Safe", classKR:"위산분비억제"},
  {en:"Lercanidipine", kr:"레르카니디핀", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Leuprolide", kr:"류프롤라이드", score:0, level:"Safe", classKR:"항종양제"},
  {en:"Levetiracetam", kr:"레비티라세탐", score:0, level:"Safe", classKR:"항전간제"},
  {en:"Levodopa/decarboxylase inhibitor", kr:"레보도파/탈탄산효소 억제제", score:0, level:"Safe", classKR:"항파킨슨제"},
  {en:"Levofloxacin", kr:"레보플록사신", score:0, level:"Safe", classKR:"항생제"},
  {en:"Lidocaine", kr:"리도카인", score:0, level:"Safe", classKR:"국소마취제"},
  {en:"Lisinopril", kr:"리시노프릴", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Lithium", kr:"리튬", score:0, level:"Safe", classKR:"항정신병약"},
  {en:"Losartan", kr:"로사르탄", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Lovastatin", kr:"로바스타틴", score:0, level:"Safe", classKR:"고지혈증 치료제"},
  {en:"Magnesium preparations", kr:"마그네슘 제제", score:0, level:"Safe", classKR:"제산제"},
  {en:"Mannitol", kr:"만니톨", score:0, level:"Safe", classKR:"이뇨제"},
  {en:"Medroxyprogesterone", kr:"메드록시프로게스테론", score:0, level:"Safe", classKR:"성호르몬제"},
  {en:"Megestrol", kr:"메게스트롤", score:0, level:"Safe", classKR:"성호르몬제"},
  {en:"Meloxicam", kr:"멜록시캄", score:0, level:"Safe", classKR:"진통제"},
  {en:"Memantine", kr:"메만틴", score:0, level:"Safe", classKR:"항치매제"},
  {en:"Mesalazine", kr:"메살라진", score:0, level:"Safe", classKR:"항염증제"},
  {en:"Metformin", kr:"메트포르민", score:0, level:"Safe", classKR:"당뇨병 치료제"},
  {en:"Methotrexate", kr:"메토트렉세이트", score:0, level:"Safe", classKR:"항종양제"},
  {en:"Methylcellulose", kr:"메틸셀룰로오스", score:0, level:"Safe", classKR:"안과용제"},
  {en:"Methylene blue", kr:"메틸렌블루", score:0, level:"Safe", classKR:"해독제"},
  {en:"Methylphenidate", kr:"메틸페니데이트", score:0, level:"Safe", classKR:"중추신경자극제"},
  {en:"Metoclopramide", kr:"메토클로프라미드", score:0, level:"Safe", classKR:"위장관운동조절제"},
  {en:"Metolazone", kr:"메톨라존", score:0, level:"Safe", classKR:"이뇨제"},
  {en:"Metoprolol", kr:"메토프롤롤", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Metronidazole", kr:"메트로니다졸", score:0, level:"Safe", classKR:"항생제"},
  {en:"Mexiletine", kr:"멕실레틴", score:0, level:"Safe", classKR:"항부정맥제"},
  {en:"Midodrine", kr:"미도드린", score:0, level:"Safe", classKR:"승압제"},
  {en:"Minocycline", kr:"미노사이클린", score:0, level:"Safe", classKR:"항생제"},
  {en:"Misoprostol", kr:"미소프로스톨", score:0, level:"Safe", classKR:"위점막보호제"},
  {en:"Mizolastine", kr:"미졸라스틴", score:0, level:"Safe", classKR:"항히스타민제"},
  {en:"Modafinil", kr:"모다피닐", score:0, level:"Safe", classKR:"중추신경자극제"},
  {en:"Moexipril", kr:"모엑시프릴", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Montelukast", kr:"몬테루카스트", score:0, level:"Safe", classKR:"천식 치료제"},
  {en:"Moxifloxacin", kr:"목시플록사신", score:0, level:"Safe", classKR:"항생제"},
  {en:"Multivitamin", kr:"종합비타민", score:0, level:"Safe", classKR:"비타민제"},
  {en:"N-acetyl-l-cysteine", kr:"아세틸시스테인", score:0, level:"Safe", classKR:"거담제"},
  {en:"Nabumetone", kr:"나부메톤", score:0, level:"Safe", classKR:"진통제"},
  {en:"Naloxone", kr:"날록손", score:0, level:"Safe", classKR:"해독제"},
  {en:"Naproxen", kr:"나프록센", score:0, level:"Safe", classKR:"진통제"},
  {en:"Naratriptan", kr:"나라트립탄", score:0, level:"Safe", classKR:"진통제"},
  {en:"Nateglinide", kr:"나테글리니드", score:0, level:"Safe", classKR:"당뇨병 치료제"},
  {en:"Nemonapride", kr:"네모나프리드", score:0, level:"Safe", classKR:"항정신병약"},
  {en:"Niacin", kr:"니아신", score:0, level:"Safe", classKR:"비타민제"},
  {en:"Nifedipine", kr:"니페디핀", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Nisoldipine", kr:"니솔디핀", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Nitrofurantoin", kr:"니트로푸란토인", score:0, level:"Safe", classKR:"항생제"},
  {en:"Nitroglycerin", kr:"니트로글리세린", score:0, level:"Safe", classKR:"항협심증제"},
  {en:"Nizatidine", kr:"니자티딘", score:0, level:"Safe", classKR:"위산분비억제"},
  {en:"Norepinephrine", kr:"노르에피네프린", score:0, level:"Safe", classKR:"승압제"},
  {en:"Norethisterone", kr:"노르에티스테론", score:0, level:"Safe", classKR:"성호르몬제"},
  {en:"Norfloxacin", kr:"노르플록사신", score:0, level:"Safe", classKR:"항생제"},
  {en:"Nystatin", kr:"니스타틴", score:0, level:"Safe", classKR:"항진균제"},
  {en:"Ofloxacin", kr:"오플록사신", score:0, level:"Safe", classKR:"항생제"},
  {en:"Olmesartan", kr:"올메사르탄", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Olopatadine", kr:"올로파타딘", score:0, level:"Safe", classKR:"항히스타민제"},
  {en:"Omeprazole", kr:"오메프라졸", score:0, level:"Safe", classKR:"위산분비억제"},
  {en:"Oxatomide", kr:"옥사토미드", score:0, level:"Safe", classKR:"항히스타민제"},
  {en:"Pamidronate", kr:"파미드로네이트", score:0, level:"Safe", classKR:"골다공증 치료제"},
  {en:"Pancrelipase", kr:"판크레리파아제", score:0, level:"Safe", classKR:"소화제"},
  {en:"Pantoprazole", kr:"판토프라졸", score:0, level:"Safe", classKR:"위산분비억제"},
  {en:"Papaverine", kr:"파파베린", score:0, level:"Safe", classKR:"위장관 진경제"},
  {en:"Pentazocine", kr:"펜타조신", score:0, level:"Safe", classKR:"진통제"},
  {en:"Pentoxifylline", kr:"펜톡시필린", score:0, level:"Safe", classKR:"혈관확장제"},
  {en:"Perindopril", kr:"페린도프릴", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Phenobarbital", kr:"페노바르비탈", score:0, level:"Safe", classKR:"항전간제"},
  {en:"Phenylephrine", kr:"페닐에프린", score:0, level:"Safe", classKR:"비충혈제거제"},
  {en:"Phenytoin", kr:"페니토인", score:0, level:"Safe", classKR:"항전간제"},
  {en:"Phytonadione", kr:"피토나디온", score:0, level:"Safe", classKR:"비타민제"},
  {en:"Pilocarpine", kr:"필로카르핀", score:0, level:"Safe", classKR:"안과용제"},
  {en:"Pioglitazone", kr:"피오글리타존", score:0, level:"Safe", classKR:"당뇨병 치료제"},
  {en:"Piperacillin", kr:"피페라실린", score:0, level:"Safe", classKR:"항생제"},
  {en:"Piroxicam", kr:"피록시캄", score:0, level:"Safe", classKR:"진통제"},
  {en:"Polycarbophil", kr:"폴리카르보필", score:0, level:"Safe", classKR:"하제"},
  {en:"Potassium", kr:"칼륨", score:0, level:"Safe", classKR:"미네랄제제"},
  {en:"Pramipexole", kr:"프라미펙솔", score:0, level:"Safe", classKR:"항파킨슨제"},
  {en:"Pravastatin", kr:"프라바스타틴", score:0, level:"Safe", classKR:"고지혈증 치료제"},
  {en:"Primidone", kr:"프리미돈", score:0, level:"Safe", classKR:"항전간제"},
  {en:"Progesterone", kr:"프로게스테론", score:0, level:"Safe", classKR:"성호르몬제"},
  {en:"Propafenone", kr:"프로파페논", score:0, level:"Safe", classKR:"항부정맥제"},
  {en:"Propranolol", kr:"프로프라놀롤", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Protamine", kr:"프로타민", score:0, level:"Safe", classKR:"해독제"},
  {en:"Pseudoephedrine", kr:"슈도에페드린", score:0, level:"Safe", classKR:"비충혈제거제"},
  {en:"Psyllium", kr:"차전자피", score:0, level:"Safe", classKR:"하제"},
  {en:"Pyrazinamide", kr:"피라진아미드", score:0, level:"Safe", classKR:"항결핵제"},
  {en:"Pyridostigmine", kr:"피리도스티그민", score:0, level:"Safe", classKR:"콜린제"},
  {en:"Pyridoxine", kr:"피리독신", score:0, level:"Safe", classKR:"비타민제"},
  {en:"Quinapril", kr:"퀴나프릴", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Rabeprazole", kr:"라베프라졸", score:0, level:"Safe", classKR:"위산분비억제"},
  {en:"Raloxifene", kr:"랄록시펜", score:0, level:"Safe", classKR:"골다공증 치료제"},
  {en:"Ramipril", kr:"라미프릴", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Repaglinide", kr:"레파글리니드", score:0, level:"Safe", classKR:"당뇨병 치료제"},
  {en:"Rifampicin", kr:"리팜피신", score:0, level:"Safe", classKR:"항결핵제"},
  {en:"Risedronate", kr:"리세드로네이트", score:0, level:"Safe", classKR:"골다공증 치료제"},
  {en:"Rivastigmine", kr:"리바스티그민", score:0, level:"Safe", classKR:"항치매제"},
  {en:"Ropinirole", kr:"로피니롤", score:0, level:"Safe", classKR:"항파킨슨제"},
  {en:"Rosiglitazone", kr:"로시글리타존", score:0, level:"Safe", classKR:"당뇨병 치료제"},
  {en:"Rosuvastatin", kr:"로수바스타틴", score:0, level:"Safe", classKR:"고지혈증 치료제"},
  {en:"Roxithromycin", kr:"록시트로마이신", score:0, level:"Safe", classKR:"항생제"},
  {en:"Salbutamol", kr:"살부타몰", score:0, level:"Safe", classKR:"기관지확장제"},
  {en:"Salsalate", kr:"살살레이트", score:0, level:"Safe", classKR:"진통제"},
  {en:"Selegiline", kr:"셀레길린", score:0, level:"Safe", classKR:"항파킨슨제"},
  {en:"Senna", kr:"센나", score:0, level:"Safe", classKR:"하제"},
  {en:"Sertraline", kr:"설트랄린", score:0, level:"Safe", classKR:"항우울제"},
  {en:"Sildenafil", kr:"실데나필", score:0, level:"Safe", classKR:"발기부전 치료제"},
  {en:"Simethicone", kr:"시메티콘", score:0, level:"Safe", classKR:"가스제거제"},
  {en:"Simvastatin", kr:"심바스타틴", score:0, level:"Safe", classKR:"고지혈증 치료제"},
  {en:"Sodium bicarbonate", kr:"탄산수소나트륨", score:0, level:"Safe", classKR:"제산제"},
  {en:"Sodium chloride", kr:"염화나트륨", score:0, level:"Safe", classKR:"전해질보충제"},
  {en:"Sotalol", kr:"소탈롤", score:0, level:"Safe", classKR:"항부정맥제"},
  {en:"Spironolactone", kr:"스피로놀락톤", score:0, level:"Safe", classKR:"이뇨제"},
  {en:"Succinylcholine", kr:"숙시닐콜린", score:0, level:"Safe", classKR:"근이완제"},
  {en:"Sucralfate", kr:"수크랄페이트", score:0, level:"Safe", classKR:"위점막보호제"},
  {en:"Sulfamethoxazole-trimethoprim", kr:"코트리목사졸", score:0, level:"Safe", classKR:"항생제"},
  {en:"Sulfasalazine", kr:"설파살라진", score:0, level:"Safe", classKR:"항염증제"},
  {en:"Sulindac", kr:"설린닥", score:0, level:"Safe", classKR:"진통제"},
  {en:"Sumatriptan", kr:"수마트립탄", score:0, level:"Safe", classKR:"진통제"},
  {en:"Tadalafil", kr:"타다라필", score:0, level:"Safe", classKR:"발기부전 치료제"},
  {en:"Tamoxifen", kr:"타목시펜", score:0, level:"Safe", classKR:"항종양제"},
  {en:"Tamsulosin", kr:"탐스로신", score:0, level:"Safe", classKR:"전립선비대증 치료제"},
  {en:"Telmisartan", kr:"텔미사르탄", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Terazosin", kr:"테라조신", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Terbinafine", kr:"테르비나핀", score:0, level:"Safe", classKR:"항진균제"},
  {en:"Testosterone", kr:"테스토스테론", score:0, level:"Safe", classKR:"성호르몬제"},
  {en:"Tetracycline", kr:"테트라사이클린", score:0, level:"Safe", classKR:"항생제"},
  {en:"Thiamine", kr:"티아민", score:0, level:"Safe", classKR:"비타민제"},
  {en:"Tianeptine", kr:"티아넵틴", score:0, level:"Safe", classKR:"항우울제"},
  {en:"Tiaprofenic acid", kr:"티아프로펜산", score:0, level:"Safe", classKR:"진통제"},
  {en:"Tibolone", kr:"티볼론", score:0, level:"Safe", classKR:"성호르몬제"},
  {en:"Timolol", kr:"티몰롤", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Tiropramide", kr:"티로프라미드", score:0, level:"Safe", classKR:"위장관 진경제"},
  {en:"Tocopherol", kr:"토코페롤", score:0, level:"Safe", classKR:"비타민제"},
  {en:"Tolperisone", kr:"톨페리손", score:0, level:"Safe", classKR:"근이완제"},
  {en:"Topiramate", kr:"토피라메이트", score:0, level:"Safe", classKR:"항전간제"},
  {en:"Torsemide", kr:"토르세미드", score:0, level:"Safe", classKR:"이뇨제"},
  {en:"Triamterene", kr:"트리암테렌", score:0, level:"Safe", classKR:"이뇨제"},
  {en:"Tuberculin purified protein derivate", kr:"튜베르쿨린", score:0, level:"Safe", classKR:"진단용약"},
  {en:"Ubidecarenone", kr:"유비데카레논", score:0, level:"Safe", classKR:"항산화제"},
  {en:"Ursodiol", kr:"우르소데옥시콜산", score:0, level:"Safe", classKR:"이담제"},
  {en:"Valproic acid", kr:"발프로산", score:0, level:"Safe", classKR:"항전간제"},
  {en:"Valsartan", kr:"발사르탄", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Vancomycin", kr:"반코마이신", score:0, level:"Safe", classKR:"항생제"},
  {en:"Vardenafil", kr:"바데나필", score:0, level:"Safe", classKR:"발기부전 치료제"},
  {en:"Varenicline", kr:"바레니클린", score:0, level:"Safe", classKR:"금연보조제"},
  {en:"Vecuronium", kr:"베쿠로늄", score:0, level:"Safe", classKR:"근이완제"},
  {en:"Verapamil", kr:"베라파밀", score:0, level:"Safe", classKR:"혈압강하제"},
  {en:"Zafirlukast", kr:"자피를루카스트", score:0, level:"Safe", classKR:"천식 치료제"},
  {en:"Zinc preparations", kr:"아연 제제", score:0, level:"Safe", classKR:"미네랄제제"},
  {en:"Zolmitriptan", kr:"졸미트립탄", score:0, level:"Safe", classKR:"진통제"},
  
  // ACB 3점 (Strong) — 엑셀 DB 기준 41종
  {en:"Amitriptyline",      kr:"아미트리프틸린",        score:3, level:"Strong",   classKR:"삼환계 항우울제"},
  {en:"Atropine",           kr:"아트로핀",              score:3, level:"Strong",   classKR:"진경제/항무스카린제"},
  {en:"Benztropine",        kr:"벤즈트로핀",            score:3, level:"Strong",   classKR:"항파킨슨제"},
  {en:"Brompheniramine",    kr:"브롬페니라민",           score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Carbinoxamine",      kr:"카르비녹사민",           score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Chlorpheniramine",   kr:"클로르페니라민",         score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Chlorpromazine",     kr:"클로르프로마진",         score:3, level:"Strong",   classKR:"항정신병약"},
  {en:"Cimetropium",        kr:"시메트로피움",           score:3, level:"Strong",   classKR:"위장관 진경제"},
  {en:"Clemastine",         kr:"클레마스틴",             score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Clomipramine",       kr:"클로미프라민",           score:3, level:"Strong",   classKR:"삼환계 항우울제"},
  {en:"Clozapine",          kr:"클로자핀",               score:3, level:"Strong",   classKR:"비정형 항정신병제"},
  {en:"Dexbrompheniramine", kr:"덱스브롬페니라민",       score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Dexchlorpheniramine",kr:"덱스클로르페니라민",     score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Dicyclomine",        kr:"디사이클로민",           score:3, level:"Strong",   classKR:"위장관 진경제"},
  {en:"Dimenhydrinate",     kr:"디멘히드리나이트",       score:3, level:"Strong",   classKR:"항구토제/항히스타민제"},
  {en:"Diphenhydramine",    kr:"디펜히드라민",           score:3, level:"Strong",   classKR:"항히스타민제/수면유도"},
  {en:"Doxepin",            kr:"독세핀",                 score:3, level:"Strong",   classKR:"삼환계 항우울제"},
  {en:"Doxylamine",         kr:"독실아민",               score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Fesoterodine",       kr:"페소테로딘",             score:3, level:"Strong",   classKR:"과민성 방광 치료제"},
  {en:"Flavoxate",          kr:"플라복세이트",           score:3, level:"Strong",   classKR:"비뇨기계 진경제"},
  {en:"Hydroxyzine",        kr:"히드록시진",             score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Imidafenacin",       kr:"이미다페나신",           score:3, level:"Strong",   classKR:"비뇨기계 진경제"},
  {en:"Imipramine",         kr:"이미프라민",             score:3, level:"Strong",   classKR:"삼환계 항우울제"},
  {en:"Meclizine",          kr:"메클리진",               score:3, level:"Strong",   classKR:"항구토제/항현훈제"},
  {en:"Mequitazine",        kr:"메퀴타진",               score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Nortriptyline",      kr:"노르트립틸린",           score:3, level:"Strong",   classKR:"항우울제"},
  {en:"Octylonium bromide", kr:"옥틸로늄 브롬화물",       score:3, level:"Strong",   classKR:"위장관 진경제"},
  {en:"Olanzapine",         kr:"올란자핀",               score:3, level:"Strong",   classKR:"항정신병약"},
  {en:"Orphenadrine",       kr:"오르페나드린",           score:3, level:"Strong",   classKR:"근이완제"},
  {en:"Oxybutynin",         kr:"옥시부티닌",             score:3, level:"Strong",   classKR:"비뇨기계 진경제"},
  {en:"Pheniramine",        kr:"페니라민",               score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Pridinol",           kr:"프리디놀",               score:3, level:"Strong",   classKR:"근이완제"},
  {en:"Procyclidine",       kr:"프로사이클리딘",         score:3, level:"Strong",   classKR:"항파킨슨제"},
  {en:"Propiverine",        kr:"프로피베린",             score:3, level:"Strong",   classKR:"비뇨기계 진경제"},
  {en:"Pyrilamine",         kr:"피릴라민",               score:3, level:"Strong",   classKR:"항히스타민제"},
  {en:"Scopolamine",        kr:"스코폴라민",             score:3, level:"Strong",   classKR:"항콜린제"},
  {en:"Scopolamine Butylbromide", kr:"스코폴라민 부틸브롬화물", score:3, level:"Strong", classKR:"위장관 진경제"},
  {en:"Solifenacin",        kr:"솔리페나신",             score:3, level:"Strong",   classKR:"비뇨기계 진경제"},
  {en:"Tolterodine",        kr:"톨테로딘",               score:3, level:"Strong",   classKR:"비뇨기계 진경제"},
  {en:"Trihexyphenidyl",    kr:"트리헥시페니딜",         score:3, level:"Strong",   classKR:"항파킨슨제"},
  {en:"Trospium",           kr:"트로스피움",             score:3, level:"Strong",   classKR:"비뇨기계 진경제"},

  // ACB 2점 (Moderate) — 엑셀 DB 기준 22종
  {en:"Amantadine",         kr:"아만타딘",               score:2, level:"Moderate", classKR:"항파킨슨제"},
  {en:"Cimetidine",         kr:"시메티딘",               score:2, level:"Moderate", classKR:"H2 차단제"},
  {en:"Clidinium",          kr:"클리디늄",               score:2, level:"Moderate", classKR:"위장관 항콜린제"},
  {en:"Cloperastine",       kr:"클로페라스틴",           score:2, level:"Moderate", classKR:"진해제"},
  {en:"Cyclobenzaprine",    kr:"사이클로벤자프린",       score:2, level:"Moderate", classKR:"근이완제"},
  {en:"Cyproheptadine",     kr:"사이프로헵타딘",         score:2, level:"Moderate", classKR:"항히스타민제"},
  {en:"Difenidol",          kr:"디페니돌",               score:2, level:"Moderate", classKR:"항현훈제"},
  {en:"Glycopyrrolate",     kr:"글리코피롤레이트",       score:2, level:"Moderate", classKR:"위장관 항콜린제"},
  {en:"Levomepromazine",    kr:"레보메프로마진",         score:2, level:"Moderate", classKR:"항정신병약"},
  {en:"Loxapine",           kr:"록사핀",                 score:2, level:"Moderate", classKR:"항정신병약"},
  {en:"Molindone",          kr:"몰린돈",                 score:2, level:"Moderate", classKR:"항정신병약"},
  {en:"Nefopam",            kr:"네포팜",                 score:2, level:"Moderate", classKR:"진통제"},
  {en:"Oxcarbazepine",      kr:"옥스카르바제핀",         score:2, level:"Moderate", classKR:"항전간제"},
  {en:"Paroxetine",         kr:"파록세틴",               score:2, level:"Moderate", classKR:"항우울제 (SSRI)"},
  {en:"Perphenazine",       kr:"퍼페나진",               score:2, level:"Moderate", classKR:"항정신병약"},
  {en:"Pethidine",          kr:"페티딘",                 score:2, level:"Moderate", classKR:"진통제"},
  {en:"Pimozide",           kr:"피모자이드",             score:2, level:"Moderate", classKR:"항정신병약"},
  {en:"Quetiapine",         kr:"쿠에티아핀",             score:2, level:"Moderate", classKR:"항정신병약"},
  {en:"Tizanidine",         kr:"티자니딘",               score:2, level:"Moderate", classKR:"근이완제"},
  {en:"Tramadol",           kr:"트라마돌",               score:2, level:"Moderate", classKR:"진통제"},
  {en:"Triprolidine",       kr:"트리프로리딘",           score:2, level:"Moderate", classKR:"항히스타민제"},
  {en:"Zotepine",           kr:"조테핀",                 score:2, level:"Moderate", classKR:"항정신병약"},

  // ACB 1점 (Weak) — 엑셀 DB 기준 50종
  {en:"Alprazolam",         kr:"알프라졸람",             score:1, level:"Weak",     classKR:"항불안제"},
  {en:"Amisulpride",        kr:"아미설프리드",           score:1, level:"Weak",     classKR:"항정신병약"},
  {en:"Aripiprazole",       kr:"아리피프라졸",           score:1, level:"Weak",     classKR:"항정신병약"},
  {en:"Baclofen",           kr:"바클로펜",               score:1, level:"Weak",     classKR:"근이완제"},
  {en:"Blonanserin",        kr:"블로난세린",             score:1, level:"Weak",     classKR:"항정신병약"},
  {en:"Bupropion",          kr:"부프로피온",             score:1, level:"Weak",     classKR:"항우울제"},
  {en:"Carbamazepine",      kr:"카르바마제핀",           score:1, level:"Weak",     classKR:"항경련제"},
  {en:"Cetirizine",         kr:"세티리진",               score:1, level:"Weak",     classKR:"항히스타민제"},
  {en:"Chlordiazepoxide",   kr:"클로르디아제폭사이드",   score:1, level:"Weak",     classKR:"항불안제"},
  {en:"Cinnarizine",        kr:"신나리진",               score:1, level:"Weak",     classKR:"항현훈제"},
  {en:"Citalopram",         kr:"시탈로프람",             score:1, level:"Weak",     classKR:"항우울제"},
  {en:"Clonazepam",         kr:"클로나제팜",             score:1, level:"Weak",     classKR:"항경련제/항불안제"},
  {en:"Codeine",            kr:"코데인",                 score:1, level:"Weak",     classKR:"진통제"},
  {en:"Desloratadine",      kr:"데슬로라타딘",           score:1, level:"Weak",     classKR:"항히스타민제"},
  {en:"Desvenlafaxine",     kr:"데스벤라팍신",           score:1, level:"Weak",     classKR:"항우울제 (SNRI)"},
  {en:"Dextromethorphan",   kr:"덱스트로메토르판",       score:1, level:"Weak",     classKR:"진해제"},
  {en:"Diazepam",           kr:"디아제팜",               score:1, level:"Weak",     classKR:"항불안제"},
  {en:"Digoxin",            kr:"디곡신",                 score:1, level:"Weak",     classKR:"강심제"},
  {en:"Emedastine",         kr:"에메다스틴",             score:1, level:"Weak",     classKR:"항히스타민제"},
  {en:"Escitalopram",       kr:"에스시탈로프람",         score:1, level:"Weak",     classKR:"항우울제"},
  {en:"Fentanyl",           kr:"펜타닐",                 score:1, level:"Weak",     classKR:"진통제"},
  {en:"Flunitrazepam",      kr:"플루니트라제팜",         score:1, level:"Weak",     classKR:"수면제"},
  {en:"Fluoxetine",         kr:"플루옥세틴",             score:1, level:"Weak",     classKR:"항우울제 (SSRI)"},
  {en:"Flurazepam",         kr:"플루라제팜",             score:1, level:"Weak",     classKR:"수면제"},
  {en:"Furosemide",         kr:"푸로세미드",             score:1, level:"Weak",     classKR:"이뇨제"},
  {en:"Guaifenesin",        kr:"구아이페네신",           score:1, level:"Weak",     classKR:"거담제"},
  {en:"Haloperidol",        kr:"할로페리돌",             score:1, level:"Weak",     classKR:"항정신병약"},
  {en:"Hydralazine",        kr:"하이드랄라진",           score:1, level:"Weak",     classKR:"혈압강하제"},
  {en:"Hydrocodone",        kr:"하이드로코돈",           score:1, level:"Weak",     classKR:"진통제"},
  {en:"Hydrocortisone",     kr:"하이드로코르티손",       score:1, level:"Weak",     classKR:"스테로이드"},
  {en:"Ketotifen",          kr:"케토티펜",               score:1, level:"Weak",     classKR:"항히스타민제"},
  {en:"Levocetirizine",     kr:"레보세티리진",           score:1, level:"Weak",     classKR:"항히스타민제"},
  {en:"Loperamide",         kr:"로페라마이드",           score:1, level:"Weak",     classKR:"지사제"},
  {en:"Loratadine",         kr:"로라타딘",               score:1, level:"Weak",     classKR:"항히스타민제"},
  {en:"Lorazepam",          kr:"로라제팜",               score:1, level:"Weak",     classKR:"항불안제"},
  {en:"Methocarbamol",      kr:"메토카르바몰",           score:1, level:"Weak",     classKR:"근이완제"},
  {en:"Midazolam",          kr:"미다졸람",               score:1, level:"Weak",     classKR:"진정제"},
  {en:"Mirtazapine",        kr:"미르타자핀",             score:1, level:"Weak",     classKR:"항우울제"},
  {en:"Morphine",           kr:"모르핀",                 score:1, level:"Weak",     classKR:"진통제"},
  {en:"Oxycodone",          kr:"옥시코돈",               score:1, level:"Weak",     classKR:"진통제"},
  {en:"Paliperidone",       kr:"팔리페리돈",             score:1, level:"Weak",     classKR:"항정신병약"},
  {en:"Prednisolone",       kr:"프레드니솔론",           score:1, level:"Weak",     classKR:"스테로이드"},
  {en:"Ranitidine",         kr:"라니티딘",               score:1, level:"Weak",     classKR:"위산분비억제"},
  {en:"Risperidone",        kr:"리스페리돈",             score:1, level:"Weak",     classKR:"항정신병약"},
  {en:"Theophylline",       kr:"테오필린",               score:1, level:"Weak",     classKR:"기관지확장제"},
  {en:"Trazodone",          kr:"트라조돈",               score:1, level:"Weak",     classKR:"항우울제/수면제"},
  {en:"Triazolam",          kr:"트리아졸람",             score:1, level:"Weak",     classKR:"수면제"},
  {en:"Trimebutine",        kr:"트리메부틴",             score:1, level:"Weak",     classKR:"위장관운동조절제"},
  {en:"Venlafaxine",        kr:"벤라팍신",               score:1, level:"Weak",     classKR:"항우울제 (SNRI)"},
  {en:"Ziprasidone",        kr:"지프라시돈",             score:1, level:"Weak",     classKR:"항정신병약"},
];

// ── 상품명 → 성분명 매핑 ─────────────────────────────────────
const BRAND_MAP = {
  // 0점 약물 상품명
  "타이레놀정":"Acetaminophen","게보린정":"Acetaminophen","판피린정":"Acetaminophen",
  "노르바스크정":"Amlodipine","아모디핀정":"Amlodipine",
  "아스피린프로텍트정":"Aspirin","아스피린정":"Aspirin",
  "리피토정":"Atorvastatin","크레스토정":"Rosuvastatin","조코정":"Simvastatin",
  "프리토정":"Losartan","디오반정":"Valsartan","아프로벨정":"Irbesartan",
  "글루코파지정":"Metformin","다이아벡스정":"Metformin",
  "넥시움정":"Esomeprazole","오메프라졸정":"Omeprazole","란스톤정":"Lansoprazole",
  "알다자이드정":"Spironolactone","알레그라정":"Fexofenadine",
  "졸로프트정":"Sertraline","심발타캡슐":"Duloxetine","아리셉트정":"Donepezil",
  "뉴론틴캡슐":"Gabapentin","케프라정":"Levetiracetam","라믹탈정":"Lamotrigine",
  "부루펜정":"Ibuprofen","낙센정":"Naproxen","쎄레브렉스캡슐":"Celecoxib",
  "볼타렌정":"Diclofenac","모빅정":"Meloxicam",
  "플라빅스정":"Clopidogrel","렉사프로정":"Escitalopram",
  "에트라빌정":"Amitriptyline","에나폰정":"Amitriptyline","토프라닐정":"Imipramine",
  "아나프라닐정":"Clomipramine","아벤틸정":"Nortriptyline","시네콴정":"Doxepin",
  "프로작캡슐":"Fluoxetine","팍실정":"Paroxetine","렉사프로정":"Escitalopram",
  "시프람정":"Citalopram","미르타불정":"Mirtazapine","레메론정":"Mirtazapine",
  "웰부트린정":"Bupropion","이펙사서방정":"Venlafaxine",
  "자이프렉사정":"Olanzapine","쿠에타핀정":"Quetiapine","리스페달정":"Risperidone",
  "에이리파이정":"Aripiprazole","클로자릴정":"Clozapine","할돌정":"Haloperidol",
  "콘타민정":"Chlorpromazine",
  "지르텍정":"Cetirizine","클라리틴정":"Loratadine","아에리우스정":"Desloratadine",
  "씨잘정":"Levocetirizine","아타락스정":"Hydroxyzine","유니히스정":"Hydroxyzine",
  "판콜에이내복액":"Chlorpheniramine","화이투벤시럽":"Chlorpheniramine",
  "래피콜데이연질캡슐":"Brompheniramine","유니좀정":"Doxylamine",
  "자낙스정":"Alprazolam","할시온정":"Triazolam","리보트릴정":"Clonazepam",
  "클로나제팜정":"Clonazepam","로라제팜정":"Lorazepam","디아제팜정":"Diazepam",
  "트리돌정":"Tramadol","울트라셋정":"Tramadol","우도락캡슐":"Tramadol",
  "리오레살정":"Baclofen","자나플렉스정":"Tizanidine","플렉세릴정":"Cyclobenzaprine",
  "노르플렉스정":"Orphenadrine","메토카르바몰정":"Methocarbamol",
  "아르탄정":"Trihexyphenidyl","트리오신정":"Trihexyphenidyl",
  "명인벤즈트로핀정":"Benztropine","환인벤즈트로핀정":"Benztropine",
  "파킨캡슐":"Amantadine","아만타딘캡슐":"Amantadine",
  "부스코판정":"Scopolamine Butylbromide","스코부틸정":"Scopolamine Butylbromide",
  "스코폴라민패취":"Scopolamine","키미테패취":"Scopolamine",
  "베시케어정":"Solifenacin","디트로판정":"Oxybutynin",
  "드리틸정":"Trospium","디트루시톨정":"Tolterodine",
  "잔탁정":"Ranitidine","타가메트정":"Cimetidine",
  "트리렙탈정":"Oxcarbazepine","테그레톨정":"Carbamazepine",
  "케토티펜정":"Ketotifen",
};

// ── 대체 약물 매핑 ────────────────────────────────────────────
const ALTERNATIVE_MAP = {
  "Amitriptyline":      ["Paroxetine","Bupropion","Citalopram","Escitalopram","Fluoxetine","Mirtazapine","Trazodone","Venlafaxine","Sertraline"],
  "Atropine":           [],
  "Benztropine":        ["Amantadine","Bromocriptine","Entacapone","Pramipexole","Ropinirole","Selegiline"],
  "Brompheniramine":    ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Carbinoxamine":      ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Chlorpheniramine":   ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Chlorpromazine":     ["Amisulpride","Aripiprazole","Haloperidol","Paliperidone","Risperidone"],
  "Clemastine":         ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Clomipramine":       ["Paroxetine","Bupropion","Citalopram","Escitalopram","Fluoxetine","Mirtazapine","Venlafaxine"],
  "Clozapine":          [],
  "Dexbrompheniramine": ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Dexchlorpheniramine":["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Dicyclomine":        ["Alverine","Fenoverine","Papaverine","Tiropramide"],
  "Dimenhydrinate":     ["Cetirizine","Loratadine","Difenidol","Betahistine"],
  "Diphenhydramine":    ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Doxepin":            ["Paroxetine","Bupropion","Citalopram","Escitalopram","Fluoxetine","Mirtazapine","Trazodone","Venlafaxine"],
  "Doxylamine":         ["Cetirizine","Desloratadine","Levocetirizine","Loratadine"],
  "Fesoterodine":       [],
  "Flavoxate":          [],
  "Hydroxyzine":        ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Imidafenacin":       [],
  "Imipramine":         ["Paroxetine","Bupropion","Citalopram","Escitalopram","Fluoxetine","Mirtazapine","Venlafaxine"],
  "Meclizine":          ["Difenidol","Betahistine"],
  "Mequitazine":        ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Nortriptyline":      ["Bupropion","Citalopram","Escitalopram","Mirtazapine","Trazodone","Sertraline"],
  "Olanzapine":         ["Amisulpride","Aripiprazole","Haloperidol","Paliperidone","Risperidone","Ziprasidone"],
  "Orphenadrine":       ["Cyclobenzaprine","Tizanidine","Baclofen","Methocarbamol","Eperisone","Tolperisone"],
  "Oxybutynin":         [],
  "Pheniramine":        ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Pridinol":           ["Cyclobenzaprine","Tizanidine","Baclofen","Methocarbamol"],
  "Procyclidine":       ["Amantadine","Entacapone","Pramipexole","Ropinirole","Selegiline"],
  "Propiverine":        [],
  "Pyrilamine":         ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Scopolamine":        [],
  "Scopolamine Butylbromide": ["Alverine","Fenoverine","Papaverine","Tiropramide"],
  "Solifenacin":        [],
  "Tolterodine":        [],
  "Trihexyphenidyl":    ["Amantadine","Entacapone","Pramipexole","Ropinirole","Selegiline"],
  "Trospium":           [],
  "Amantadine":         ["Bromocriptine","Entacapone","Pramipexole","Ropinirole","Selegiline"],
  "Cimetidine":         ["Esomeprazole","Famotidine","Lansoprazole","Omeprazole","Pantoprazole"],
  "Clidinium":          ["Alverine","Fenoverine","Papaverine","Tiropramide"],
  "Cloperastine":       ["Dextromethorphan","Benzonatate"],
  "Cyclobenzaprine":    ["Baclofen","Methocarbamol","Eperisone","Tolperisone"],
  "Cyproheptadine":     ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Difenidol":          ["Cinnarizine","Betahistine"],
  "Glycopyrrolate":     ["Alverine","Fenoverine","Papaverine","Tiropramide"],
  "Levomepromazine":    ["Amisulpride","Aripiprazole","Haloperidol","Paliperidone","Risperidone"],
  "Loxapine":           ["Amisulpride","Aripiprazole","Haloperidol","Paliperidone","Risperidone"],
  "Molindone":          ["Amisulpride","Aripiprazole","Haloperidol","Paliperidone","Risperidone"],
  "Nefopam":            ["Acetaminophen","Celecoxib","Diclofenac","Ibuprofen","Meloxicam","Naproxen"],
  "Oxcarbazepine":      ["Carbamazepine","Gabapentin","Lamotrigine","Levetiracetam","Valproic acid"],
  "Paroxetine":         ["Duloxetine","Sertraline","Tianeptine"],
  "Perphenazine":       ["Amisulpride","Aripiprazole","Haloperidol","Paliperidone","Risperidone"],
  "Pethidine":          ["Acetaminophen","Celecoxib","Diclofenac","Ibuprofen","Meloxicam"],
  "Pimozide":           ["Amisulpride","Aripiprazole","Haloperidol","Paliperidone","Risperidone"],
  "Quetiapine":         ["Amisulpride","Aripiprazole","Haloperidol","Paliperidone","Risperidone"],
  "Tizanidine":         ["Baclofen","Methocarbamol","Eperisone","Tolperisone"],
  "Tramadol":           ["Acetaminophen","Celecoxib","Diclofenac","Ibuprofen","Meloxicam","Naproxen"],
  "Triprolidine":       ["Cetirizine","Desloratadine","Levocetirizine","Loratadine","Fexofenadine"],
  "Zotepine":           ["Amisulpride","Aripiprazole","Haloperidol","Paliperidone","Risperidone"],
  "Carbamazepine":      ["Levetiracetam","Lamotrigine"],
  "Cetirizine":         ["Fexofenadine","Azelastine","Bepotastine","Olopatadine"],
  "Cinnarizine":        ["Betahistine"],
  "Citalopram":         ["Duloxetine","Sertraline","Tianeptine"],
  "Clonazepam":         ["Levetiracetam"],
  "Codeine":            ["Acetaminophen","Celecoxib","Diclofenac","Ibuprofen","Naproxen"],
  "Desloratadine":      ["Fexofenadine","Azelastine","Bepotastine","Olopatadine"],
  "Dextromethorphan":   ["Benzonatate"],
  "Digoxin":            ["Dobutamine","Dopamine"],
  "Escitalopram":       ["Duloxetine","Sertraline","Tianeptine"],
  "Fentanyl":           ["Acetaminophen","Celecoxib","Diclofenac","Ibuprofen","Meloxicam"],
  "Fluoxetine":         ["Duloxetine","Sertraline","Tianeptine"],
  "Furosemide":         ["Hydrochlorothiazide","Indapamide","Spironolactone","Torsemide"],
  "Haloperidol":        ["Lithium","Nemonapride"],
  "Hydralazine":        ["Amlodipine","Atenolol","Bisoprolol","Enalapril","Losartan","Valsartan"],
  "Ketotifen":          ["Fexofenadine","Azelastine","Bepotastine","Olopatadine"],
  "Levocetirizine":     ["Fexofenadine","Azelastine","Bepotastine","Olopatadine"],
  "Loratadine":         ["Fexofenadine","Azelastine","Bepotastine","Olopatadine"],
  "Methocarbamol":      ["Eperisone","Tolperisone"],
  "Mirtazapine":        ["Duloxetine","Sertraline","Tianeptine"],
  "Morphine":           ["Acetaminophen","Celecoxib","Diclofenac","Ibuprofen","Meloxicam"],
  "Oxycodone":          ["Acetaminophen","Celecoxib","Diclofenac","Ibuprofen","Meloxicam"],
  "Ranitidine":         ["Esomeprazole","Famotidine","Lansoprazole","Omeprazole","Pantoprazole"],
  "Theophylline":       ["Salbutamol"],
  "Trazodone":          ["Duloxetine","Sertraline","Tianeptine"],
  "Trimebutine":        ["Domperidone","Metoclopramide"],
  "Venlafaxine":        ["Duloxetine","Sertraline","Tianeptine"],
};
